/*

	Copyright (C) 2009-2010 TETSUHARU HANADA <rhpenguine@gmail.com>
	All rights reserved.
	
	You can redistribute and/or modify this software under the 
	LESSER GPL version 2.1.
	See also LICENSE.txt and LICENSE_LGPL2.1.txt.

*/

//
// librhplog.so
//

#ifndef _RHP_LOG_H_
#define _RHP_LOG_H_

#define RHP_LOG_LV_DEBUG					0
#define RHP_LOG_LV_ERR						1
#define RHP_LOG_LV_WARN						2
#define RHP_LOG_LV_NOTICE					3
#define RHP_LOG_LV_INFO						4
#define RHP_LOG_LV_DBGERR					5


#define RHP_LOG_SRC_NONE					0
#define RHP_LOG_SRC_MAIN					1
#define RHP_LOG_SRC_SYSPXY				2
#define RHP_LOG_SRC_IKEV2					3
#define RHP_LOG_SRC_UI						4
#define RHP_LOG_SRC_VPNMNG				5
#define RHP_LOG_SRC_CFG						6
#define RHP_LOG_SRC_AUTHCFG				7
#define RHP_LOG_SRC_AUTH					8
#define RHP_LOG_SRC_NETMNG				9


extern int rhp_log_init(int process_role);
extern int rhp_log_cleanup(int process_role);


#define RHP_LOG_MAX_RECORD_BUF_SIZE			2048
#define RHP_LOG_MAX_BIN_RECORD_BUF_SIZE	1024


/*
 rhp_log : Write an event log.
 	 	 	 	 	 	 	 	A max buffer size for one event log's record is limited to RHP_LOG_MAX_RECORD_BUF_SIZE.

 event_source  :  ID of where this event occurs. (See RHP_LOG_SRC_XXX)

 vpn_realm_id : VPN Realm's ID or RHP_HTTP_BUS_BTX_ALL_REALMS(0xFFFFFFFF) for common events.

 level : Event Log's level. (See RHP_LOG_LV_XXX)

 log_id : Event Log's ID.

 format  :
  'b' : 1B data. (char,unsigned char)
  'w' : 2B data. (short,unsigned short)
  'W' : 2B data. (short,unsigned short) BE(swapped)
  'd' : 4B data. (int)
  'D' : 4B data. (int) BE(swapped)
  'q' : 8B data. (long long,unsigned long long)
  'Q' : 8B data. (long long,unsigned long long) BE(swapped)
  's' : String.  (with '\0' terminated.)
  'j' : 4B data. (unsigned int)
  'J' : 4B data. (unsigned int) BE(swapped)
  'u' : unsigned long data.
  'U' : unsigned long data. BE(swapped)
  'x' : unsigned long data. (long, address) (HEX)
  'X' : unsigned long data (long, address) BE(swapped)(HEX)
  'p' : A pointer of binary dump data.
  'a' : A pointer of binary dump data. (string)
	'E' : Error code. 4B data
  '4' : IPv4 address. 4B data (Network Byte Order)
  '6' : IPv6 address. 16B data(pointer).
  'M' : MAC address. 6B data(pointer).
	'G' : IKE SPI (8bytes)
	'H' : ESP SPI (4bytes)/u32 (Network Byte Order)
	'I' : A pointer of rhp_ikev2_id.
	'e' : A pointer of rhp_eap_id.
	'A' : A pointer of rhp_ip_addr.
	'F' : A pointer of rhp_if_entry.
	'N'	: A pointer of rhp_vpn->unique_id. (16bytes)
	'L' : A value with a label.(int)
	'K' : A pointer of received rhp_ikev2_mesg.
	'V' : A pointer of rhp_vpn.
	'P' : A pointer of rhp_ikesa.
	'C' : A pointer of rhp_childsa.
	'i' : if_index. IF name is resolved by if_indextoname().
	't' : time_t (Sytem ticks)
	'T' : time_t (Since epoc-time)
	'r' : A pointer of rhp_radius_session.
	'R' : A pointer of rhp_radius_mesg.
	'n' : A pointer of rhp_nhrp_req_session.
	'B' : A pointer of rhp_nhrp_mesg.


 args    : Event Log's args.
              Each '#ARG?#' marker of a log message line defined in rhp_event_log.xml
              will be replaced to each arg. '?' in a '#ARG?#' marker means a position in
              args. This '?' begins from 0 and is just incremented.

			(e.g.)

			  (Source code)
				RHP_LOG_I(RHP_LOG_SRC_VPNMNG,vpn->vpn_realm_id,RHP_LOG_ID_VPN_ADDED,"IAsN",&(vpn->peer_id),&(vpn->peer_addr),vpn->peer_fqdn,vpn->unique_id);

			  (rhp_event_log.xml)
  			<event_log id="106" tag="VPN_ADDED">
    			<![CDATA[<label style="font-weight:bold;">VPN added.</label><br> Peer ID:#ARG0#, #ARG1#, #ARG2# UID:#ARG3#]]>
  			</event_log>

  			#ARG0# : &(vpn->peer_id)
  			#ARG1# : &(vpn->peer_addr)
  			#ARG2# : vpn->peer_fqdn
  			#ARG3# : vpn->unique_id


  	  (cf)
  	   - rockhopper/misc/mk_trace_fmt.sh

 */
extern void rhp_log(unsigned long event_source,unsigned long vpn_realm_id,
		unsigned long level,unsigned long log_id, /*char* format,(top of va_args)*/ ... );

/*
 RHP_LOG_D			: Debug
 RHP_LOG_DE			: Debug Error
 RHP_LOG_E			: Error
 RHP_LOG_W			: Warning
 RHP_LOG_N			: Notice
 RHP_LOG_I			: Info
 RHP_LOG_X_ALL	: All realms
 */
#define RHP_LOG_D(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_DEBUG,(log_id),__VA_ARGS__)

#define RHP_LOG_DE(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_DBGERR,(log_id),__VA_ARGS__)

// RHP_HTTP_BUS_BTX_ALL_REALMS : 0xFFFFFFFF
#define RHP_LOG_D_ALL(event_source,log_id,...)\
	rhp_log((event_source),0xFFFFFFFF,RHP_LOG_LV_DEBUG,(log_id),__VA_ARGS__)

#define RHP_LOG_E(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_ERR,(log_id),__VA_ARGS__)

// RHP_HTTP_BUS_BTX_ALL_REALMS : 0xFFFFFFFF
#define RHP_LOG_E_ALL(event_source,log_id,...)\
	rhp_log((event_source),0xFFFFFFFF,RHP_LOG_LV_ERR,(log_id),__VA_ARGS__)

#define RHP_LOG_W(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_WARN,(log_id),__VA_ARGS__)

// RHP_HTTP_BUS_BTX_ALL_REALMS : 0xFFFFFFFF
#define RHP_LOG_W_ALL(event_source,log_id,...)\
	rhp_log((event_source),0xFFFFFFFF,RHP_LOG_LV_WARN,(log_id),__VA_ARGS__)

#define RHP_LOG_N(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_NOTICE,(log_id),__VA_ARGS__)

// RHP_HTTP_BUS_BTX_ALL_REALMS : 0xFFFFFFFF
#define RHP_LOG_N_ALL(event_source,log_id,...)\
	rhp_log((event_source),0xFFFFFFFF,RHP_LOG_LV_NOTICE,(log_id),__VA_ARGS__)

#define RHP_LOG_I(event_source,vpn_realm_id,log_id,...)\
	rhp_log((event_source),(vpn_realm_id),RHP_LOG_LV_INFO,(log_id),__VA_ARGS__)

// RHP_HTTP_BUS_BTX_ALL_REALMS : 0xFFFFFFFF
#define RHP_LOG_I_ALL(event_source,log_id,...)\
	rhp_log((event_source),0xFFFFFFFF,RHP_LOG_LV_INFO,(log_id),__VA_ARGS__)

typedef void (*RHP_LOG_GET_RECORD_NUM_CB)(long num,void* ctx);
extern int rhp_log_get_record_num(RHP_LOG_GET_RECORD_NUM_CB callback,void* ctx);

typedef void (*RHP_LOG_RESET_CB)(int err,void* ctx);
extern int rhp_log_reset(RHP_LOG_RESET_CB callback,void* ctx);

#define RHP_LOG_SAVE_TYPE_XML		1
#define RHP_LOG_SAVE_TYPE_TXT		2
typedef void (*RHP_LOG_SAVE_CB)(int err,void* ctx);
extern int rhp_log_save(int file_type,char* file_name,unsigned long vpn_realm_id,int limit_num,RHP_LOG_SAVE_CB callback,void* ctx);

extern void rhp_log_enable_debug_level(int flag);
extern int rhp_log_debug_level_enabled();

extern void rhp_log_disable(int flag);


#define RHP_LOG_ID_LOG_FILE_CREATED															1
//
// 2 -- 99 are reserved for manually assigned event IDs.
//
#define RHP_LOG_ID_CONNECT_I_ERR																100
#define RHP_LOG_ID_CONNECT_I_START															101
#define RHP_LOG_ID_CLOSE_VPN																		102
#define RHP_LOG_ID_CLOSE_VPN_ERR																103
#define RHP_LOG_ID_VPN_ESTABLISHED															104
#define RHP_LOG_ID_VPN_DELETED																	105
#define RHP_LOG_ID_VPN_ADDED																		106
#define RHP_LOG_ID_MAIN_CREATE_REALM														107
#define RHP_LOG_ID_MAIN_CREATE_REALM_ERR												108
#define RHP_LOG_ID_SYSPXY_CREATE_REALM													109
#define RHP_LOG_ID_SYSPXY_CREATE_REALM_ERR											110
#define RHP_LOG_ID_MAIN_DELETE_REALM														111
#define RHP_LOG_ID_MAIN_DELETE_REALM_ERR												112
#define RHP_LOG_ID_SYSPXY_DELETE_REALM													113
#define RHP_LOG_ID_SYSPXY_DELETE_REALM_ERR											114
#define RHP_LOG_ID_MAIN_UPDATE_REALM														115
#define RHP_LOG_ID_MAIN_UPDATE_REALM_ERR												116
#define RHP_LOG_ID_SYSPXY_UPDATE_REALM													117
#define RHP_LOG_ID_SYSPXY_UPDATE_REALM_ERR											118
#define RHP_LOG_ID_CFG_PARSE_ERR																119
#define RHP_LOG_ID_AUTHCFG_PARSE_ERR														120
#define RHP_LOG_ID_NO_MY_AUTH_INFO															121
#define RHP_LOG_ID_NO_MY_PSK																		122
#define RHP_LOG_ID_NO_MY_CERT																		123
#define RHP_LOG_ID_NO_PEER_AUTH_INFO														124
#define RHP_LOG_ID_PARSE_GLOBAL_CFG_ERR													125
#define RHP_LOG_ID_UPDATE_GLOBAL_CFG														126
#define RHP_LOG_ID_UPDATE_GLOBAL_CFG_ERR												127
#define RHP_LOG_ID_MEMDBG_FREE_NULL_PT													128
#define RHP_LOG_ID_MEMDBG_FREE_INVALID_PT												129
#define RHP_LOG_ID_MEMDBG_FREE_DUP_PT														130
#define RHP_LOG_ID_MEMDBG_FREE_MAY_DUP_PT												131
#define RHP_LOG_ID_MEMDBG_FREE_MAY_DUP_PT2											132
#define RHP_LOG_ID_UI_HTTP_NOT_PERMITTED												133
#define RHP_LOG_ID_UI_HTTP_HANDLE_ERR														134
#define RHP_LOG_ID_UI_SYSPXY_NOT_PERMITTED											135
#define RHP_LOG_ID_UI_SYSPXY_HANDLE_ERR													136
#define RHP_LOG_ID_UI_UPDATE_MY_KEY_INFO												137
#define RHP_LOG_ID_UI_UPDATE_MY_KEY_INFO_ERR										138
#define RHP_LOG_ID_UI_UPDATE_PEER_KEY														139
#define RHP_LOG_ID_UI_UPDATE_PEER_KEY_ERR												140
#define RHP_LOG_ID_MEMDBG_FREE_ZERO_INVALID_SIZE								141
#define RHP_LOG_ID_UI_DELETE_PEER_KEY														142
#define RHP_LOG_ID_UI_DELETE_PEER_KEY_ERR												143
#define RHP_LOG_ID_UI_UPDATE_MY_CERT														144
#define RHP_LOG_ID_UI_UPDATE_CA_CERT														145
#define RHP_LOG_ID_UI_UPDATE_MY_CERT_ERR												146
#define RHP_LOG_ID_UI_UPDATE_CA_CERT_ERR												147
#define RHP_LOG_ID_UI_UPDATE_CERT_ERR														148
#define RHP_LOG_ID_UI_UPDATE_ADMIN															149
#define RHP_LOG_ID_UI_UPDATE_ADMIN_ERR													150
#define RHP_LOG_ID_UI_DELETE_ADMIN															151
#define RHP_LOG_ID_UI_DELETE_ADMIN_ERR													152
#define RHP_LOG_ID_BUG_TRC																			153
#define RHP_LOG_ID_SAVE_CFG_FILE_ERR														154
#define RHP_LOG_ID_AUTH_ADMIN_INVALID_REALM											155
#define RHP_LOG_ID_AUTH_ADMIN_FAILED														156
#define RHP_LOG_ID_AUTH_ADMIN_ERR																157
#define RHP_LOG_ID_ADMIN_AUTH_OK																158
#define RHP_LOG_ID_ADMIN_REJECTED																159
#define RHP_LOG_ID_ADMIN_INVALID_REALM													160
#define RHP_LOG_ID_CFG_SYS																			161
#define RHP_LOG_ID_AUTO_RECONNECT_CANCELED											162
#define RHP_LOG_ID_EXEC_AUTO_RECONNECT													163
#define RHP_LOG_ID_EXEC_AUTO_RECONNECT_ERR											164
#define RHP_LOG_ID_TX_CFG_REQ																		165
#define RHP_LOG_ID_RX_CFG_REQ																		166
#define RHP_LOG_ID_RX_CFG_REQ_CP_PAYLOAD												167
#define RHP_LOG_ID_RX_CFG_REQ_CP_PAYLOAD_NOT_SUPPORTED_CFG_TYPE	168
#define RHP_LOG_ID_RX_CFG_REQ_ASSIGN_INTERNAL_ADDR_FAILED				169
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_ADDRESS							170
#define RHP_LOG_ID_RX_CFG_REQ_INVALID_INTERNAL_IF								171
#define RHP_LOG_ID_RX_CFG_REQ_NO_INTERNAL_IF_NETMASK						172
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_SUBNET_ADDRESS			173
#define RHP_LOG_ID_RX_CFG_REQ_NO_INTERNAL_DNS_SERVER						174
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_DNS_SERVER					175
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_DNS_SUFFIX								176
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_SUBNET							177
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_GATEWAY							178
#define RHP_LOG_ID_RX_CFG_REQ_SUPPORTED_ATTRIBUTES							179
#define RHP_LOG_ID_RX_CFG_RESP_CP_PAYLOAD												180
#define RHP_LOG_ID_RX_CFG_RESP_NOT_SUPPORTED_CFG_TYPE						181
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_ADDRESS									182
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_GATEWAY									183
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_SUBNET									184
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_DNS_SERVER							185
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_DNS_SUFFIX							186
#define RHP_LOG_ID_RX_CFG_RESP_PEER_IS_ACCESSPOINT							187
#define RHP_LOG_ID_RX_CFG_RESP_PEER_IS_NOT_ACCESSPOINT					188
#define RHP_LOG_ID_TX_CFG_REQ_REKEY															189
#define RHP_LOG_ID_TX_CFG_REQ_REKEY_ERR													190
#define RHP_LOG_ID_RX_CFG_REQ_ERR																191
#define RHP_LOG_ID_RX_CFG_REQ_OK																192
#define RHP_LOG_ID_TX_CFG_REQ_ERR																193
#define RHP_LOG_ID_RX_CFG_RESP_ERR															194
#define RHP_LOG_ID_RX_CFG_RESP_OK																195
#define RHP_LOG_ID_UI_UPDATE_CERT_NO_MY_AUTH										196
#define RHP_LOG_ID_IF_CACHE_STATUS      												197
#define RHP_LOG_ID_OPEN_SOCKET_RETRY_ERR												198
#define RHP_LOG_ID_OPEN_SOCKET_RETRY_OK													199
#define RHP_LOG_ID_IKEV2_VERIFY_COOKIE_OK											200
#define RHP_LOG_ID_IKEV2_VERIFY_COOKIE_ERR										201
#define RHP_LOG_ID_IKEV2_VERIFY_COOKIE_ERR_GEN_NEW_COOKIE			202
#define RHP_LOG_ID_IKEV2_TX_ALLOC_COOKIE_REQ_ERR								203
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_PEER					204
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_PEER_ERR			205
#define RHP_LOG_ID_RX_IKE_SA_INIT_RETRY_KE											206
#define RHP_LOG_ID_RX_IKE_SA_INIT_RETRY_KE_ERR									207
#define RHP_LOG_ID_RX_IKE_SA_INIT_COOKIE_OK											208
#define RHP_LOG_ID_RX_IKE_SA_INIT_COOKIE_ERR										209
#define RHP_LOG_ID_RX_IKE_SA_INIT_PARSE_SA_PAYLOAD							210
#define RHP_LOG_ID_RX_IKE_SA_INIT_PARSE_KE_PAYLOAD							211
#define RHP_LOG_ID_RX_IKE_SA_INIT_PARSE_N_I_R_PAYLOAD						212
#define RHP_LOG_ID_RX_IKE_SA_INIT_CERTREQ_PAYLOADS							213
#define RHP_LOG_ID_RX_IKE_SA_INIT_NO_CERTREQ_PAYLOAD						214
#define RHP_LOG_ID_RX_IKE_SA_INIT_CERTREQ_PAYLOAD_UNSUPPORTED_ENCODE		215
#define RHP_LOG_ID_RX_IKE_SA_INIT_CERTREQ_PAYLOAD_TOO_MANY_REQS					216
#define RHP_LOG_ID_RX_IKE_SA_INIT_N_HTTP_CERT_LOOKUP_SUPPORTED_PAYLOAD	217
#define RHP_LOG_ID_RX_IKE_SA_INIT_V_PAYLOAD_PEER_IS_ROCKHOPPER	218
#define RHP_LOG_ID_RX_IKE_SA_INIT_V_PAYLOAD											219
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_COOKIE_PAYLOAD_ERR	220
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_NO_N_COOKIE_PAYLOAD			221
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_INVALID_KE_PAYLOAD_ERR		222
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_N_ERR_PAYLOAD						223
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_ERR_PAYLOAD_ERR	224
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_SA_PAYLOAD_ERR			225
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_I_R_PAYLOAD_ERR	226
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_KE_PAYLOAD_ERR			227
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_CERTREQ_PAYLOAD_ERR	228
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_HTTP_CERT_LOOKUP_PAYLOAD_ERR	229
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_V_PAYLOAD_ERR			230
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PRF_ALG_ERR							231
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_INTEG_ALG_ERR						232
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_ENCR_ALG_ERR							233
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_OK												234
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_ERR											235
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_WAIT_RETRY								236
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_PARSE_SA_PAYLOAD_ERR			237
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_PARSE_N_I_R_PAYLOAD_ERR		238
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_PARSE_KE_PAYLOAD_ERR			239
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_PARSE_V_PAYLOAD_ERR				240
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_OK												241
#define RHP_LOG_ID_RX_IKE_SA_INIT_REQ_ERR												242
#define RHP_LOG_ID_IKEV2_TX_REQ_ERR															243
#define RHP_LOG_ID_IKEV2_RX_REQ_ERR															244
#define RHP_LOG_ID_IKEV2_RX_RESP_ERR														245
#define RHP_LOG_ID_IKEV2_RX_VERIFY_RESP_ERR											246
#define RHP_LOG_ID_IKEV2_RETRANSMIT_RESPONSE										247
#define RHP_LOG_ID_IKEV2_RX_VERIFY_REQ_NEW_REQ									248
#define RHP_LOG_ID_IKEV2_RX_VERIFY_REQ_ERR											249
#define RHP_LOG_ID_IKEV2_IPV4_RX_ERR														250
#define RHP_LOG_ID_IKEV2_EXEC_RETRANSMIT												251
#define RHP_LOG_ID_IKEV2_RETRANSMIT_ERR													252
#define RHP_LOG_ID_RX_INVALID_IKEV2_MESG												253
#define RHP_LOG_ID_IKEV2_PARSE_RX_PAYLOAD_ERR										254
#define RHP_LOG_ID_IKEV2_PARSE_RX_MESG_ERR											255
#define RHP_LOG_ID_DNS_PXY_READ_RESOLV_CONF											256
#define RHP_LOG_ID_DNS_PXY_ACTIVATED														257
#define RHP_LOG_ID_DNS_PXY_DEACTIVATED													258
#define RHP_LOG_ID_RX_PKT_REJECTED															259
#define RHP_LOG_ID_RX_UNSUPPORTED_PKT_REJECTED									260
#define RHP_LOG_ID_IKEV2_RX_NEW_IKE_SA_INIT_REQ      						261
#define RHP_LOG_ID_CHILDSA_PFS_BUT_NO_DH_ALG_IN_PROP						262
#define RHP_LOG_ID_VPN_ESTABLISH_ERR														263
#define RHP_LOG_ID_IKE_AUTH_NEW_REQ_PKT_ERR 										264
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_ID_I_PAYLOAD       				265
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_ID_R_PAYLOAD       				266
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_AUTH_PAYLOAD       				267
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_CERT_PAYLOADS      				268
#define RHP_LOG_ID_RX_IKE_AUTH_NO_CERT_PAYLOAD  								269
#define RHP_LOG_ID_RX_IKE_AUTH_NOT_SUPPORTED_CERT_ENCODING      270
#define RHP_LOG_ID_RX_IKE_AUTH_TOO_MANY_CERT_PAYLOADS   				271
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_N_ERR_PAYLOAD       				272
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_PARSE_N_ERR_PAYLOAD_ERR     273
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_PARSE_ID_R_PAYLOAD_ERR      274
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_ID_R_PAYLOAD_INVALID_PEER_ID	275
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_AUTH_PAYLOAD_ERR        		276
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_CERT_PAYLOAD_ERR        		277
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_OK  												278
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_ERR 												279
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_CERTREQ_PAYLOADS   				280
#define RHP_LOG_ID_RX_IKE_AUTH_NO_CERTREQ_PAYLOAD       				281
#define RHP_LOG_ID_RX_IKE_AUTH_UNSUPPORTED_CERTREQ_ENCODING     282
#define RHP_LOG_ID_RX_IKE_AUTH_TOO_MANY_CERTREQ_PAYLOADS        283
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_ID_I_PAYLOAD_ERR       284
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_ID_R_PAYLOAD_ERR       285
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_AUTH_PAYLOAD_ERR       286
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_CERT_PAYLOAD_ERR       287
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_CERTREQ_PAYLOAD_ERR    288
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_NO_SA_PAYLOAD_FOR_CHILDSA    289
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_NO_TS_I_PAYLOAD_FOR_CHILDSA  290
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_NO_TS_R_PAYLOAD_FOR_CHILDSA  291
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_OK   												292
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_TX_ERROR_NOTIFY      				293
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_ERR  												294
#define RHP_LOG_ID_IKEV2_EXEC_RETRANSMIT_ERR										295
#define RHP_LOG_ID_RX_IKE_AUTH_SIGN_OK  												296
#define RHP_LOG_ID_RX_IKE_AUTH_SIGN_ERR 												297
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_OK   								298
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_ERR  								299
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_ERR_TX_ERR_NOTIFY    300
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_AND_SIGN_OK  				301
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_AND_SIGN_ERR 				302
#define RHP_LOG_ID_RX_IKE_AUTH_VERIFY_AUTH_AND_SIGN_ERR_TX_ERR_NOTIFY   	303
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_VERIFY_AUTH_OK      				304
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_VERIFY_AUTH_ERR     				305
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_VERIFY_AUTH_ERR_TX_ERR_NOTIFY       	306
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_VERIFY_AUTH_AND_SIGN_OK     307
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_VERIFY_AUTH_ERR      				308
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_VERIFY_AUTH_AND_SIGN_ERR     309
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_VERIFY_AUTH_ERR_TX_ERR_NOTIFY        	310
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_VERIFY_AUTH_AND_SIGN_ERR_TX_ERR_NOTIFY 311
#define RHP_LOG_ID_VERIFY_PSK_REALM_NOT_DEFINED 								312
#define RHP_LOG_ID_PEER_PSK_NOT_DEFINED 												313
#define RHP_LOG_ID_INVALID_PEER_PSK     												314
#define RHP_LOG_ID_GENERATE_MY_SIGNATURE_ERR    								315
#define RHP_LOG_ID_ENUM_MY_CERT_ERR     												316
#define RHP_LOG_ID_ANY_PEERS_PSK_DEFINED_BUT_IGNORED    				317
#define RHP_LOG_ID_ANY_PEERS_PSK_DEFINED        								318
#define RHP_LOG_ID_PEER_PSK_DEFINED_BUT_IGNORED 								319
#define RHP_LOG_ID_PEER_PSK_DEFINED     												320
#define RHP_LOG_ID_VERIFY_PEER_SIGNATURE_ERR    								321
#define RHP_LOG_ID_VERIFY_RSASIG_REALM_NOT_DEFINED      				322
#define RHP_LOG_ID_GET_CA_CERT_DIGEST_ERR       								323
#define RHP_LOG_ID_GET_NO_MY_CERT_ERR														324
#define RHP_LOG_ID_NO_PEER_CFG  																325
#define RHP_LOG_ID_MY_VPN_ID																		326
#define RHP_LOG_ID_MY_VPN_ID_RESOLVE_ERR												327
#define RHP_LOG_ID_RX_CFG_REQ_CP_PAYLOAD_ATTRS									328
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_WINS								329
#define RHP_LOG_ID_RX_CFG_RESP_APP_VER													330
#define RHP_LOG_ID_UI_UPDATE_CERTIFICATE_FILE										331
#define RHP_LOG_ID_UI_UPDATE_CERTIFICATE_FILE_ERR								332
#define RHP_LOG_ID_REKEYED_IKESA_INITIATOR											333
#define RHP_LOG_ID_REKEYED_IKESA_INITIATOR_ERR									334
#define RHP_LOG_ID_REKEYED_CHILDSA_INITIATOR_ERR2								335
#define RHP_LOG_ID_REKEYED_CHILDSA_INITIATOR										336
#define RHP_LOG_ID_REKEYED_CHILDSA_INITIATOR_ERR								337
#define RHP_LOG_ID_REKEYED_IKESA_RESPONDER											338
#define RHP_LOG_ID_REKEY_IKESA_TX_ERR_RESP											339
#define RHP_LOG_ID_REKEYED_IKESA_RESPONDER_ERR									340
#define RHP_LOG_ID_REKEYED_CHILDSA_RESPONDER										341
#define RHP_LOG_ID_REKEY_CHILDSA_TX_ERR_RESP										342
#define RHP_LOG_ID_REKEY_CHILDSA_RESPONDER_ERR									343
#define RHP_LOG_ID_RX_REKEY_REQ_ERR															344
#define RHP_LOG_ID_RX_REKEY_REP_ERR															345
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_EAP_TX_ERR_NOTIFY						346
#define RHP_LOG_ID_RX_EAP_REQ_INIT_TX_ERR_NOTIFY								347
#define RHP_LOG_ID_RX_EAP_REQ_PEND_TX_ERR_NOTIFY								348
#define RHP_LOG_ID_RX_EAP_REQ_CB_TX_ERR_NOTIFY									349
#define RHP_LOG_ID_EAP_NO_PEER_KEY	350
#define RHP_LOG_ID_EAP_SERVER_FAILED_TO_PROCESS_EAP_MESG	351
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_STATE	352
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_CHALLENGE_REQ	353
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_SUCCESS_REQ	354
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_FAILURE_REQ	355
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_EAP_FAILURE	356
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_EAP_SUCCESS	357
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_INVALID_EAP_FRAME	358
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_INVALID_MSCHAPV2_CODE	359
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_INVALID_MSCHAPV2_CODE2	360
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_PEER_AUTH_SUCCESS	361
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_PEER_AUTH_FAILED	362
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_PEER_AUTH_WAIT_RETRY	363
#define RHP_LOG_ID_EAP_SERVER_AUTH_CONTINUE	364
#define RHP_LOG_ID_EAP_SERVER_AUTH_COMPLETED	365
#define RHP_LOG_ID_EAP_SERVER_AUTH_FAILED	366
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_RESP1	367
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_RESP2	368
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_RESP3	369
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_INVALID_RESP	370
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_TX_REQ1	371
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_TX_REQ2	372
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_TX_REQ3	373
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_TX_INVALID_REQ	374
#define RHP_LOG_ID_CERT_EXPIRED	375
#define RHP_LOG_ID_CERT_VERIFY_ERR	376
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_SIGN_AUTH_ERR_TX_ERR_NOTIFY	377
#define RHP_LOG_ID_CERT_VERIFY_CHECK_CRL	378
#define RHP_LOG_ID_CERT_VERIFY_OK	379
#define RHP_LOG_ID_CERT_EXPIRED_BUG_IGNORED	380
#define RHP_LOG_ID_LOADED_X509_CERT_DER	381
#define RHP_LOG_ID_LOADED_X509_CERT_PEM	382
#define RHP_LOG_ID_LOADED_X509_CRL_PEM	383
#define RHP_LOG_ID_LOAD_PRIV_KEY_NOT_FOUND	384
#define RHP_LOG_ID_LOAD_PRIV_KEY_LOAD_ERR	385
#define RHP_LOG_ID_LOAD_MY_CERT_NOT_FOUND	386
#define RHP_LOG_ID_LOAD_MY_CERT_LOAD_ERR	387
#define RHP_LOG_ID_LOAD_CA_CERTS_NOT_FOUND	388
#define RHP_LOG_ID_LOAD_CA_CERTS_LOAD_ERR	389
#define RHP_LOG_ID_LOAD_CA_CERTS_LOAD_ERR_2	390
#define RHP_LOG_ID_LOAD_CRL_NOT_FOUND	391
#define RHP_LOG_ID_LOAD_CRL_LOAD_ERR	392
#define RHP_LOG_ID_ALLOC_CERT_STORE_ERR	393
#define RHP_LOG_ID_UPDATE_CERT_STORE_ERR	394
#define RHP_LOG_ID_PRIV_KEY_LOADED	395
#define RHP_LOG_ID_RX_HTTP_MESG_TOO_LONG	396
#define RHP_LOG_ID_CREATED_CHILDSA_RESPONDER	397
#define RHP_LOG_ID_CREATED_CHILDSA_RESPONDER_ERR	398
#define RHP_LOG_ID_CREATED_CHILDSA_INITIATOR_ERR2	399
#define RHP_LOG_ID_CREATED_CHILDSA_INITIATOR	400
#define RHP_LOG_ID_CREATED_CHILDSA_INITIATOR_ERR	401
#define RHP_LOG_ID_IKE_SA_INIT_TX_ERR_NOTIFY	402
#define RHP_LOG_ID_IKE_SA_INIT_TX_ERR_NOTIFY_FAILED	403
#define RHP_LOG_ID_CHILDSA_STATE	404
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_RESP_NO_NAT	405
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_RESP_PEER_BEHIND_A_NAT	406
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_RESP_LOCAL_BEHIND_A_NAT	407
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_RESP_ERR	408
#define RHP_LOG_ID_RX_INFO_NATT_RESP_NO_NAT	409
#define RHP_LOG_ID_RX_INFO_NATT_RESP_PEER_BEHIND_A_NAT	410
#define RHP_LOG_ID_RX_INFO_NATT_RESP_LOCAL_BEHIND_A_NAT	411
#define RHP_LOG_ID_RX_INFO_NATT_RESP_ERR	412
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_REQ_NO_NAT	413
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_REQ_PEER_BEHIND_A_NAT	414
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_REQ_LOCAL_BEHIND_A_NAT	415
#define RHP_LOG_ID_RX_IKE_SA_INIT_NATT_REQ_ERR	416
#define RHP_LOG_ID_RX_INFO_NATT_REQ_NO_NAT	417
#define RHP_LOG_ID_RX_INFO_NATT_REQ_PEER_BEHIND_A_NAT	418
#define RHP_LOG_ID_RX_INFO_NATT_REQ_LOCAL_BEHIND_A_NAT	419
#define RHP_LOG_ID_RX_INFO_NATT_REQ_ERR	420
#define RHP_LOG_ID_IKESA_STATE	421
#define RHP_LOG_ID_RX_INFO_REQ	422
#define RHP_LOG_ID_RX_INFO_REQ_ERR	423
#define RHP_LOG_ID_RX_INFO_RESP	424
#define RHP_LOG_ID_RX_INFO_RESP_ERR	425
#define RHP_LOG_ID_RX_DELETE_IKESA_REQ	426
#define RHP_LOG_ID_RX_DELETE_IKESA_REQ_IGNORED	427
#define RHP_LOG_ID_RX_DELETE_IKESA_REQ_ERR	428
#define RHP_LOG_ID_RX_DELETE_CHILDSA_REQ_NOT_FOUND	429
#define RHP_LOG_ID_RX_DELETE_CHILDSA_REQ	430
#define RHP_LOG_ID_RX_DELETE_CHILDSA_REQ_ERR	431
#define RHP_LOG_ID_RX_DELETE_IKESA_RESP	432
#define RHP_LOG_ID_RX_DELETE_CHILDSA_RESP_NOT_FOUND	433
#define RHP_LOG_ID_RX_DELETE_CHILDSA_RESP	434
#define RHP_LOG_ID_PEER_ADDR_V4_PORT_CHANGED	435
#define RHP_LOG_ID_RX_CREATE_CHILD_SA_REQ_TX_ERR_NOTIFY	436
#define RHP_LOG_ID_IF_CACHE_ADDR_STATUS_CHANED	437
#define RHP_LOG_ID_DBG_DROP_IKEV2_PKT	438
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_START_CONN_ERR	439
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_START_CONN	440
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_N_I	441
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_N_R	442
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_SK_D	443
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_VALUES_ENC	444
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_VALUES_DEC	445
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_VALUES_INTEG_INB	446
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_KEY_VALUES_INTEG_OUTB	447
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_DH_SHAREDKEY	448
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_N_I	449
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_N_R	450
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_SK_D	451
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_VALUES_ENC	452
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_VALUES_DEC	453
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_VALUES_INTEG_INB	454
#define RHP_LOG_ID_DBG_CHILDSA_GENERATED_NEW_KEY_VALUES_INTEG_OUTB	455
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_DH_SHAREDKEY	456
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_N_I	457
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_N_R	458
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_SKEYSEED	459
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_D	460
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_AI	461
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_AR	462
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_EI	463
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_ER	464
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_PI	465
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_PR	466
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_DH_SHAREDKEY	467
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_N_I	468
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_N_R	469
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_SKEYSEED	470
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_D	471
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_AI	472
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_AR	473
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_EI	474
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_ER	475
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_PI	476
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_PR	477
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_D	478
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_AI	479
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_AR	480
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_EI	481
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_ER	482
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_PI	483
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_PR	484
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_D	485
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_AI	486
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_AR	487
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_EI	488
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_ER	489
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_PI	490
#define RHP_LOG_ID_DBG_IKESA_INTEG_ERR_SK_PR	491
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_D	492
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_AI	493
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_AR	494
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_EI	495
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_ER	496
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_PI	497
#define RHP_LOG_ID_DBG_IKESA_DECRYPT_ERR_SK_PR	498
#define RHP_LOG_ID_INTERNAL_ADDRESS_CACHE_FOUND	501
#define RHP_LOG_ID_INTERNAL_ADDRESS_RESERVED	502
#define RHP_LOG_ID_INTERNAL_ADDRESS_NEW	503
#define RHP_LOG_ID_INTERNAL_ADDRESS_NO_POOL	504
#define RHP_LOG_ID_INTERNAL_ADDRESS_FAILED_TO_ASSIGN	505
#define RHP_LOG_ID_IKE_AUTH_IKE_IPV4_PORT_CHANGED	506
#define RHP_LOG_ID_HTTP_SERVER_OPEN_ERR	507
#define RHP_LOG_ID_EAP_SERVER_AUTH_ERROR	508
#define RHP_LOG_ID_HTTP_SERVER_OPEN	509
#define RHP_LOG_ID_NO_REQUESTED_CA_FOUND	510
#define RHP_LOG_ID_VERIFY_PSK_RX_INVALID_PEER_ID_TYPE	511
#define RHP_LOG_ID_VERIFY_EAP_SUP_RX_INVALID_PEER_ID_TYPE	512
#define RHP_LOG_ID_VERIFY_EAP_SUP_REALM_NOT_DEFINED	513
#define RHP_LOG_ID_VERIFY_RSASIG_RX_INVALID_PEER_ID_TYPE	514
#define RHP_LOG_ID_VERIFY_RSASIG_RX_INVALID_PEER_CERT	515
#define RHP_LOG_ID_VERIFY_RSASIG_NO_MY_CERT_STORE	516
#define RHP_LOG_ID_EAP_PEER_KEY_FOUND	517
#define RHP_LOG_ID_EAP_NOT_AUTHENTICATOR	518
#define RHP_LOG_ID_EAP_SERVER_ACTUAL_REALM_FOUND	519
#define RHP_LOG_ID_VERIFY_EAP_SUP_DEF_EAP_SERVER_USED	520
#define RHP_LOG_ID_VERIFY_EAP_SUP_NO_DEF_EAP_SERVER	521
#define RHP_LOG_ID_VERIFY_EAP_SUP_REALM_FOUND	522
#define RHP_LOG_ID_UI_UPDATE_PEER_EAP_KEY	523
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_INTERNAL_PEER_IPV4	524
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_INTERNAL_PEER_MAC	525
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_INTERNAL_PEER_IS_HUB	526
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_INTERNAL_PEER_IS_MESH_NODE	527
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_BAD_PEER_ADDR_NOTIFIED	528
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_REP_PEER_IS_ALSO_HUB	529
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_REP_PEER_IS_MESH_NODE	530
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_REP_PEER_IS_HUB	531
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_REP_STATIC_PEER_IS_CONFIGURED	532
#define RHP_LOG_ID_CONNECT_I_CONN_EXISTS	533
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_NO_CERT_PAYLOAD	534
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_NO_CERT_PAYLOAD	535
#define RHP_LOG_ID_VERIFY_RSASIG_RX_INVALID_MY_ID_TYPE	536
#define RHP_LOG_ID_DUMP_TS_PAYLOAD	537
#define RHP_LOG_ID_NO_CERT_INFO_LOADED	538
#define RHP_LOG_ID_NO_PEER_PSK_FOUND	539
#define RHP_LOG_ID_CONNECT_I_PEER_FQDN_RESOLV_ERR	540
#define RHP_LOG_ID_CONNECT_I_NO_REALM_FOUND	541
#define RHP_LOG_ID_CONNECT_I_MY_ID_NOT_CONFIGURED	542
#define RHP_LOG_ID_CONNECT_I_VIF_NOT_CONFIGURED	543
#define RHP_LOG_ID_CONNECT_I_NO_PEER_CFG_FOUND	544
#define RHP_LOG_ID_CONNECT_I_PEER_IP_NOT_CONFIGURED	545
#define RHP_LOG_ID_CONNECT_I_CFG_IF_NOT_ACTIVE	546
#define RHP_LOG_ID_ADMIN_NOBODY_USER_NOT_ALLOWED	547
#define RHP_LOG_ID_ADMIN_NOBODY_USER_ALLOWED_ONLY_FROM_LOOPBACK	548
#define RHP_LOG_ID_UI_HTTP_NOBODY_USER_NOT_ALLOWED_ACTION	549
#define RHP_LOG_ID_HTTP_SERVER_START_RETRY_ERR	550
#define RHP_LOG_ID_AUTH_ADMIN_AUTH_COOKIE_FAILED	551
#define RHP_LOG_ID_AUTH_ADMIN_AUTH_FAILED	552
#define RHP_LOG_ID_ADMIN_NOBODY_USER_CFG_ALLOWED	553
#define RHP_LOG_ID_ADMIN_NOBODY_USER_CFG_UPDATED	554
#define RHP_LOG_ID_UI_HTTP_NOBODY_USER_NOT_ALLOWED_URI	555
#define RHP_LOG_ID_IKE_SA_INIT_RESP_TX_ALL_CAS_CERTREQ	556
#define RHP_LOG_ID_IKE_SA_INIT_RESP_NO_REQUESTED_CA_FOUND	557
#define RHP_LOG_ID_IKE_SA_INIT_RESP_REQUESTED_CA_FOUND	558
#define RHP_LOG_ID_RTMAP_CACHE_STATUS	559
#define RHP_LOG_ID_SRC_IF_BY_DEFAULT_FOUTE_ADDED	560
#define RHP_LOG_ID_SRC_IF_BY_DEFAULT_FOUTE_DELETED	561
#define RHP_LOG_ID_NETSOCK_OPEN	562
#define RHP_LOG_ID_NETSOCK_OPEN_ERR	563
#define RHP_LOG_ID_NETSOCK_CLOSE	564
#define RHP_LOG_ID_UPLOAD_PKCS12_FILE_OK	565
#define RHP_LOG_ID_UPLOAD_MY_PRIVATE_KEY_PEM_FILE_OK	566
#define RHP_LOG_ID_UPLOAD_MY_CERT_PEM_FILE_OK	567
#define RHP_LOG_ID_UPLOAD_CA_CERT_PEM_FILE_OK	568
#define RHP_LOG_ID_UPLOAD_CRL_PEM_FILE_OK	569
#define RHP_LOG_ID_UPLOAD_CERT_FILE_ERR	570
#define RHP_LOG_ID_MY_VPN_ID_EAP_SUP_ENABLED	571
#define RHP_LOG_ID_UI_UPDATE_MY_KEY_INFO_EAP_SUP_ENABLED	572
#define RHP_LOG_ID_DBG_EAP_SUP_MSK_GEN	573
#define RHP_LOG_ID_DBG_EAP_SUP_MSK_VRFY	574
#define RHP_LOG_ID_DBG_EAP_AUTH_MSK	575
#define RHP_LOG_ID_EAP_SUP_MSK_NOT_AVAILABLE	576
#define RHP_LOG_ID_EAP_AUTH_MSK_NOT_AVAILABLE	577
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_STATE	578
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_GEN_CHALLENGE_REPLY	579
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_TOO_SHORT_CHALLENGE_DATA	580
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_INVALID_CHALLENGE_LEN	581
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_TOO_SHORT_CHALLENGE_PACKET	582
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_CHALLENGE_REQ	583
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_GEN_CHALLENGE_REPLY_ERR	584
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_INVALID_SUCCESS_REQ	585
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_GEN_SUUCESS_REPLY_ERR	586
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_SUCCESS_REQ	587
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_EAP_SUCCESS	588
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_RETRY_ALLOWED	589
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_RETRY_NOT_ALLOWED	590
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_WAITING_FOR_NEW_KEY	591
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_WAITING_FOR_NEW_KEY_ERR	592
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_GEN_FAILURE_REPLY_ERR	593
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ	594
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_INVALID_EAP_MESG_HDR	595
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_EAP_FAILURE	596
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_INVALID_MSCHAPV2_HDR	597
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_NEW_KEY	598
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_PROCESS_FAILURE_REQ_NEW_KEY_ERR	599
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_INVALID_EAP_MESG_IN_SUCCESS_RESP	600
#define RHP_LOG_ID_EAP_PEER_GET_USER_KEY_CACHED	601
#define RHP_LOG_ID_EAP_PEER_GET_USER_KEY_ERR	602
#define RHP_LOG_ID_EAP_PEER_AUTH_CONTINUE	603
#define RHP_LOG_ID_EAP_PEER_AUTH_COMPLETED	604
#define RHP_LOG_ID_EAP_PEER_AUTH_ERROR	605
#define RHP_LOG_ID_EAP_PEER_AUTH_FAILED	606
#define RHP_LOG_ID_EAP_PEER_GET_USER_KEY_CONFIGURED	607
#define RHP_LOG_ID_EAP_PEER_CLEAR_CACHED_USER_KEY	608
#define RHP_LOG_ID_EAP_PEER_FAILED_TO_PROCESS_EAP_MESG	609
#define RHP_LOG_ID_VPN_CLEAR_ALL	610
#define RHP_LOG_ID_VPN_CLEAR_ALL_ERR	611
#define RHP_LOG_ID_IKE_QCD_TX_ERR_RESP	612
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_VPN_CLEARED	613
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_QCD_TOKEN	614
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_QCD_TOKENS	615
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_NO_IKESA	616
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_NO_VPN	617
#define RHP_LOG_ID_IKE_QCD_TX_TOKEN	618
#define RHP_LOG_ID_IKE_QCD_TX_TOKEN_DATA	619
#define RHP_LOG_ID_IKE_QCD_RX_INVALID_PEER_TOKEN	620
#define RHP_LOG_ID_IKE_QCD_RX_PEER_TOKEN	621
#define RHP_LOG_ID_IKE_QCD_RX_PEER_TOKEN_DATA	622
#define RHP_LOG_ID_IKE_QCD_GEN_TX_TOKEN_ERR	623
#define RHP_LOG_ID_IKE_QCD_SECRET	624
#define RHP_LOG_ID_IKE_MOBIKE_TX_ERR_NOTIFY	625
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV4_ADDR_NOTIFY	626
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_SUPPORTED_NOTIFY	627
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_SUPPORTED_NOTIFY	628
#define RHP_LOG_ID_IKE_MOBIKE_RX_NO_NATS_ALLOWED_DETECTED	629
#define RHP_LOG_ID_IKE_MOBIKE_RX_INVALID_NO_NATS_ALLOWED_NOTIFY	630
#define RHP_LOG_ID_IKE_MOBIKE_RX_NO_NATS_ALLOWED_NOTIFY	631
#define RHP_LOG_ID_IKE_MOBIKE_RX_ADDITIONAL_ADDRS_NOTIFY	632
#define RHP_LOG_ID_IKE_MOBIKE_RX_INVALID_ADDITIONAL_ADDRS_NOTIFY	633
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_SUPPORTED_NOTIFY	634
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_SUPPORTED_NOTIFY	635
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_NO_ADDITIONAL_ADDR_NOTIFY	636
#define RHP_LOG_ID_IKE_MOBIKE_I_AUTH_ENABLED	637
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_AUTH_REP_ERR	638
#define RHP_LOG_ID_IKE_MOBIKE_R_AUTH_PEER_DISABLED	639
#define RHP_LOG_ID_IKE_MOBIKE_R_AUTH_ENABLED	640
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_AUTH_REQ_ERR	641
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REP_TX_RX_COOKIE2	642
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_INFO_REP	643
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_INFO_REP_ERR	644
#define RHP_LOG_ID_IKE_MOBIKE_INFO_RX_UPDATE_SA_ADDRESS_NOTIFY	645
#define RHP_LOG_ID_IKE_MOBIKE_INFO_RX_COOKIE2_NOTIFY	646
#define RHP_LOG_ID_IKE_MOBIKE_INFO_RX_INVALID_COOKIE2_NOTIFY	647
#define RHP_LOG_ID_IKE_MOBIKE_R_UPDATE_PATH	648
#define RHP_LOG_ID_IKE_MOBIKE_R_RT_CK_TX_COOKIE2_NOTIFY	649
#define RHP_LOG_ID_IKE_MOBIKE_R_RT_CK_TX_PROBE	650
#define RHP_LOG_ID_IKE_MOBIKE_R_RT_CK_TX_PROBE_ERR	651
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REQ	652
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REQ_ERR	653
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REQ_DISABLED	654
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REQ_NO_UPDATE_SA_ADDR	655
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REQ_RT_CK_DISABLED	656
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REQ	657
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REQ_ERR	658
#define RHP_LOG_ID_IKE_MOBIKE_I_NAT_GW_REF_ADDR_TX_UPDATE_SA_ADDR	659
#define RHP_LOG_ID_IKE_MOBIKE_I_NAT_GW_REF_TX_COOKIE2	660
#define RHP_LOG_ID_IKE_MOBIKE_I_NAT_GW_REF_TX_ERR	661
#define RHP_LOG_ID_IKE_MOBIKE_NAT_GW_REF_ADDR_CHANGED	662
#define RHP_LOG_ID_IKE_MOBIKE_NAT_GW_REF_ADDR_CHANGED_ERR	663
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REP_INVALID_COOKIE2_LEN	664
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REP_INVALID_COOKIE2	665
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REP	666
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INFO_REP_ERR	667
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_INFO_REP_INVALID_COOKIE2_LEN	668
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_INFO_REP_INVALID_COOKIE2	669
#define RHP_LOG_ID_IKE_MOBIKE_RX_REQ_ERR	670
#define RHP_LOG_ID_IKE_MOBIKE_RX_REP_ERR	671
#define RHP_LOG_ID_IKE_MOBIKE_BUILD_PATH_MAP	672
#define RHP_LOG_ID_IKE_MOBIKE_BUILD_PATH_MAP_ERR	673
#define RHP_LOG_ID_IKE_MOBIKE_RX_RT_CK_PROBE_REP	674
#define RHP_LOG_ID_IKE_MOBIKE_RX_RT_CK_PROBE_REP_IGNORED	675
#define RHP_LOG_ID_IKE_MOBIKE_RX_RT_CK_PROBE_REP_ERR	676
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_TX_PROBE_2	677
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_UPDATE_SA_ADDR_NOTIFY	678
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_COOKIE2_NOTIFY	679
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_NO_NATS_ALLOWED_NOTIFY	680
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_ERR	681
#define RHP_LOG_ID_IKE_MOBIKE_I_RT_CK_FOUND_NEW_PATH	682
#define RHP_LOG_ID_IKE_MOBIKE_I_UPDATE_PATH	683
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_UPDATE_SA_ADDR	684
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_ERR	685
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_CONT	686
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_CONT_ERR	687
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_TX_PROBE_1	688
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_INIT	689
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_INIT_ERR	690
#define RHP_LOG_ID_IKE_MOBIKE_I_START_ROUTABILITY_CHECK	691
#define RHP_LOG_ID_IKE_MOBIKE_I_START_ROUTABILITY_CHECK_ERR	692
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED_PENDING	693
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED	694
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED_ERR	695
#define RHP_LOG_ID_IKE_MOBIKE_RX_UNACCEPTABLE_ADDR_ERR	696
#define RHP_LOG_ID_IKE_MOBIKE_I_RX_INVALID_PEER_COOKIE2	697
#define RHP_LOG_ID_IKE_MOBIKE_R_RX_INVALID_PEER_COOKIE2	698
#define RHP_LOG_ID_IKE_MOBIKE_I_PEER_ADDITIONAL_ADDR	699
#define RHP_LOG_ID_IKE_MOBIKE_I_PEER_NO_ADDITIONAL_ADDR	700
#define RHP_LOG_ID_RX_IKEV2_PLAIN_MESG_ERR_NOTIFY	701
#define RHP_LOG_ID_IKE_QCD_RX_INVALID_ERR_RESP	702
#define RHP_LOG_ID_CERT_URL	703
#define RHP_LOG_ID_CERT_URL_INVALID_DN	704
#define RHP_LOG_ID_CERT_URL_IGNORED	705
#define RHP_LOG_ID_HTTP_CLT_GET_TIMEOUT	706
#define RHP_LOG_ID_HTTP_CLT_GET_CONN_ERR	707
#define RHP_LOG_ID_HTTP_CLT_GET_DNS_OK	708
#define RHP_LOG_ID_HTTP_CLT_GET_DNS_ERR	709
#define RHP_LOG_ID_HTTP_CLT_GET_START	710
#define RHP_LOG_ID_HTTP_CLT_GET_START_ERR	711
#define RHP_LOG_ID_HTTP_CLT_GET_START_TASK_ERR	712
#define RHP_LOG_ID_HTTP_CLT_GET_RESP_ERR	713
#define RHP_LOG_ID_HTTP_CLT_GET_RECV_ERR	714
#define RHP_LOG_ID_HTTP_CLT_GET_COMP_ERR	715
#define RHP_LOG_ID_HTTP_CLT_GET_LAST_COMP	716
#define RHP_LOG_ID_HTTP_CLT_GET_COMP	717
#define RHP_LOG_ID_HTTP_CLT_GET_HANDLE_ERR	718
#define RHP_LOG_ID_HTTP_CLT_GET_RESP_DATA	719
#define RHP_LOG_ID_RX_IKE_AUTH_N_HTTP_CERT_LOOKUP_SUPPORTED_PAYLOAD	720
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_N_HTTP_CERT_LOOKUP_PAYLOAD_ERR	721
#define RHP_LOG_ID_IKE_QCD_TX_TOKEN_2	722
#define RHP_LOG_ID_RX_IKE_PKT_VIA_UNCONFIGURED_IF	723
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV4_ADDR_NOTIFY_DST_NAT_ADDR	724
#define RHP_LOG_ID_CONNECT_I_RSLV_PEER_ADDRS	725
#define RHP_LOG_ID_CONNECT_I_RSLV_PEER_ADDRS_ERR	726
#define RHP_LOG_ID_CONNECT_I_NO_REALM_FOUND_2	727
#define RHP_LOG_ID_CONNECT_I_NO_PEER_CFG_FOUND_2	728
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_START_CONN_ERR_2	729
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_START_CONN_2	730
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_I_RSLV_PEER_ADDRS	731
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_RSLV_PEER_ADDRS_ERR	732
#define RHP_LOG_ID_RX_IKE_AUTH_HASH_URL_BAD_LENGTH	733
#define RHP_LOG_ID_RX_IKE_AUTH_HASH_URL_NOT_SUPPORTED_PROTO	734
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_HASH_URL_TX_ERR_NOTIFY	735
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_INFO_REP	736
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_INFO_REP_ERR	737
#define RHP_LOG_ID_IKE_MOBIKE_R_NAT_T_DYN_DISABLED	738
#define RHP_LOG_ID_IKE_MOBIKE_R_NAT_T_DYN_ENABLED	739
#define RHP_LOG_ID_IKE_MOBIKE_I_NAT_T_DYN_DISABLED	740
#define RHP_LOG_ID_IKE_MOBIKE_I_NAT_T_DYN_ENABLED	741
#define RHP_LOG_ID_IKE_MOBIKE_INFO_RX_COOKIE2_NOTIFY_2	742
#define RHP_LOG_ID_IKE_MOBIKE_R_INFO_REP_TX_RX_COOKIE2_RESP	743
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_COOKIE2_NOTIFY_RESP	744
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_WAITING	745
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_REVOKED	746
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_QCD_TOKEN_VAL	747
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_ROUTE	748
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_ROUTE_ERR	749
#define RHP_LOG_ID_IKEV2_RETRANSMIT_REQ_ERR	750
#define RHP_LOG_ID_IKE_RX_ERR_NOTIFY	751
#define RHP_LOG_ID_IKE_TX_ERR_NOTIFY	752
#define RHP_LOG_ID_IKESA_NO_PROPOSAL_CHOSEN	753
#define RHP_LOG_ID_CHILDSA_NO_PROPOSAL_CHOSEN	754
#define RHP_LOG_ID_VPN_MOBIKE_CLEAR_ADDITIONAL_ADDR_CACHE	755
#define RHP_LOG_ID_MOBIKE_I_START_RT_CHECK_ERR	756
#define RHP_LOG_ID_MOBIKE_I_START_RT_CHECK_BY_UI	757
#define RHP_LOG_ID_MOBIKE_I_START_RT_CHECK_BY_UI_PENDING	758
#define RHP_LOG_ID_MOBIKE_I_START_RT_CHECK_BY_UI_ERR	759
#define RHP_LOG_ID_REMOTE_CFG_SVR_ADDR_POOL_BAD_END_ADDR	760
#define RHP_LOG_ID_RX_IKEV2_PLAIN_MESG_PRIVATE_ERR_NOTIFY	761
#define RHP_LOG_ID_DBG_OPENSSL_DH_GENERATE_KEY_KEY_LEN	762
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_IKESA_STATE	763
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_IKESA_STATE_QCD_TOKENS	764
#define RHP_LOG_ID_RX_CFG_RESP_FWD_PKT_DEST_INTERNALNET_TO_DEV	765
#define RHP_LOG_ID_RX_CFG_RESP_FWD_ANY_DNS_QUERIES_ENABLED	766
#define RHP_LOG_ID_RX_CFG_RESP_FWD_ANY_DNS_QUERIES_DISABLED	767
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_INVALID_IDENTITY_REQ	768
#define RHP_LOG_ID_EAP_PEER_MSCHAPV2_RX_IDENTITY_REQ_NO_USER_NAME	769
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_GEN_EAP_IDENTITY_REQ	770
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_IDENTITY_RESP	771
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_RX_IDENTITY_RESP_ERR	772
#define RHP_LOG_ID_RX_IKE_EAP_RESP_N_ERR_PAYLOAD	773
#define RHP_LOG_ID_RX_IKE_EAP_RESP_PARSE_N_ERR_PAYLOAD_ERR	774
#define RHP_LOG_ID_EAP_SERVER_MSCHAPV2_INVALID_EAP_IDENTITY_RESP	775
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_WAITING_NO_CAND	776
#define RHP_LOG_ID_IKE_MOBIKE_RX_ADDITIONAL_ADDRS_IGNORED_TOO_MANY	777
#define RHP_LOG_ID_IKE_MOBIKE_RX_ADDITIONAL_ADDRS_IGNORED_SAME_SRC_IP	778
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV4_ADDR_NOTIFY_DST_NAT_ADDR_IGNORED	779
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV4_ADDR_NOTIFY_DST_NAT_ADDR_CHECK_ERR	780
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV4_ADDR_NOTIFY_DST_NAT_ADDR_2	781
#define RHP_LOG_ID_HTTP_CLT_GET_RX_INVALID_URL	782
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_HASH_URL_GET_CERT_ERR	783
#define RHP_LOG_ID_RX_IKE_AUTH_REP_HASH_URL_GET_CERT_ERR	784
#define RHP_LOG_ID_VPN_MOBIKE_CLEAR_ADDITIONAL_ADDR_CACHE_ERR	785
#define RHP_LOG_ID_VPN_EAP_SUP_CLEAR_USER_KEY_CACHE	786
#define RHP_LOG_ID_VPN_EAP_SUP_CLEAR_USER_KEY_CACHE_ERR	787
#define RHP_LOG_ID_CONNECT_I_RSLV_PEER_ADDR_START	788
#define RHP_LOG_ID_HTTP_SERVER_ACCEPT_ERR_TOO_MANY_SKS	789
#define RHP_LOG_ID_HTTP_CLT_GET_INVALID_SERVER_NAME	790
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED_EQ_OR_HIGHER_IF_EXISTS	791
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED_BUT_IGNORED	792
#define RHP_LOG_ID_IKE_MOBIKE_R_NET_OUTAGE_DETECTED	793
#define RHP_LOG_ID_IKE_MOBIKE_R_NET_OUTAGE_FINISHED_NO_RT_CK	794
#define RHP_LOG_ID_IKE_MOBIKE_R_NET_OUTAGE_FINISHED_RT_CK	795
#define RHP_LOG_ID_RX_IKE_AUTH_N_REALM_ID_PAYLOAD	796
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_N_REALM_ID_PAYLOAD_ERR	797
#define RHP_LOG_ID_TX_REALM_ID_N_PAYLOAD	798
#define RHP_LOG_ID_RX_IKE_AUTH_N_INVALID_REALM_ID_PAYLOAD	799
#define RHP_LOG_ID_RX_IKE_AUTH_N_INVALID_REALM_ID_PAYLOAD_LEN	800
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY_2	801
#define RHP_LOG_ID_IKE_MOBIKE_BUILD_PATH_MAP_V6	802
#define RHP_LOG_ID_RX_PKT_V6_REJECTED	803
#define RHP_LOG_ID_DNS_PXY_READ_RESOLV_CONF_V6	804
#define RHP_LOG_ID_DNS_PXY_ACTIVATED_V6	805
#define RHP_LOG_ID_DNS_PXY_DEACTIVATED_V6	806
#define RHP_LOG_ID_IKEV2_RX_VERIFY_RESP_V6_ERR	807
#define RHP_LOG_ID_IKEV2_RETRANSMIT_RESPONSE_V6	808
#define RHP_LOG_ID_IKEV2_RX_VERIFY_REQ_V6_ERR	809
#define RHP_LOG_ID_IKEV2_IPV6_RX_ERR	810
#define RHP_LOG_ID_IKEV2_RETRANSMIT_REQ_V6_ERR	811
#define RHP_LOG_ID_IKEV2_EXEC_RETRANSMIT_V6	812
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_ROUTE_V6	813
#define RHP_LOG_ID_IKEV2_IKE_SA_INIT_TRY_SECONDARY_ROUTE_V6_ERR	814
#define RHP_LOG_ID_RX_IKEV2_PLAIN_MESG_ERR_NOTIFY_V6	815
#define RHP_LOG_ID_RX_IKEV2_PLAIN_MESG_PRIVATE_ERR_NOTIFY_V6	816
#define RHP_LOG_ID_PEER_ADDR_V6_PORT_CHANGED	817
#define RHP_LOG_ID_IKE_AUTH_IKE_IPV6_PORT_CHANGED	818
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY_DST_NAT_ADDR	819
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY_DST_NAT_ADDR_2	820
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY_DST_NAT_ADDR_IGNORED	821
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY_DST_NAT_ADDR_CHECK_ERR	822
#define RHP_LOG_ID_IKE_MOBIKE_RX_NO_NATS_ALLOWED_DETECTED_V6	823
#define RHP_LOG_ID_IKE_MOBIKE_RX_ADDITIONAL_ADDRS_IGNORED_SAME_SRC_IP_V6	824
#define RHP_LOG_ID_IKE_MOBIKE_RX_ADDITIONAL_ADDRS_NOTIFY_V6	825
#define RHP_LOG_ID_IKE_MOBIKE_I_PEER_ADDITIONAL_ADDR_V6	826
#define RHP_LOG_ID_IKE_MOBIKE_R_UPDATE_PATH_V6	827
#define RHP_LOG_ID_IKE_MOBIKE_I_UPDATE_PATH_V6	828
#define RHP_LOG_ID_IKE_MOBIKE_RX_RT_CK_PROBE_REP_V6	829
#define RHP_LOG_ID_IKE_MOBIKE_I_TX_NO_NATS_ALLOWED_NOTIFY_V6	830
#define RHP_LOG_ID_IKE_MOBIKE_I_RT_CK_FOUND_NEW_PATH_V6	831
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_TX_PROBE_1_V6	832
#define RHP_LOG_ID_IKE_QCD_TX_ERR_RESP_V6	833
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_VPN_CLEARED_V6	834
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_QCD_TOKENS_V6	835
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_IKESA_STATE_V6	836
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_IKESA_STATE_QCD_TOKENS_V6	837
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_QCD_TOKEN_V6	838
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_BAD_QCD_TOKEN_VAL_V6	839
#define RHP_LOG_ID_IKE_QCD_RX_ERR_RESP_NO_IKESA_V6	840
#define RHP_LOG_ID_IKE_QCD_RX_INVALID_ERR_RESP_V6	841
#define RHP_LOG_ID_INTERNAL_ADDRESS_V4_FAILED_TO_ASSIGN	842
#define RHP_LOG_ID_INTERNAL_ADDRESS_V6_FAILED_TO_ASSIGN	843
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_ADDRESS	844
#define RHP_LOG_ID_RX_CFG_REQ_NO_INTERNAL_DNS_SERVER_V6	845
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_DNS_SERVER	846
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_SUBNET	847
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_GATEWAY	848
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_WINS	849
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_ADDRESS_V6	850
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_DNS_SERVER_V6	851
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_GATEWAY_V6	852
#define RHP_LOG_ID_RX_CFG_RESP_FWD_PKT_DEST_INTERNALNET_TO_DEV_V6	853
#define RHP_LOG_ID_RX_CFG_RESP_INTERNAL_SUBNET_V6	854
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_INTERNAL_PEER_IPV6	855
#define RHP_LOG_ID_CONNECT_I_PEER_IPV6_DISABLED	856
#define RHP_LOG_ID_DNS_PXY_READ_RESOLV_CONF_ERR	857
#define RHP_LOG_ID_DNS_PXY_READ_RESOLV_CONF_ERR_V6	858
#define RHP_LOG_ID_DNS_PXY_ENABLE_REDIRECT	859
#define RHP_LOG_ID_DNS_PXY_ENABLE_REDIRECT_V6	860
#define RHP_LOG_ID_DNS_PXY_DISABLE_REDIRECT	861
#define RHP_LOG_ID_DNS_PXY_DISABLE_REDIRECT_V6	862
#define RHP_LOG_ID_IKE_MOBIKE_R_TX_ADDITIONAL_IPV6_ADDR_NOTIFY	863
#define RHP_LOG_ID_RX_CFG_RESP_FWD_ANY_DNS_QUERIES_ENABLED_V6	864
#define RHP_LOG_ID_RX_CFG_RESP_FWD_ANY_DNS_QUERIES_DISABLED_V6	865
#define RHP_LOG_ID_CONNECT_I_IPV4_NOT_ENABLED	866
#define RHP_LOG_ID_CONNECT_I_IPV6_NOT_ENABLED	867
#define RHP_LOG_ID_CONNECT_I_CFG_IF_NO_SRC_IP	868
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_ADDRESS_NOT_ASSIGNED	869
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_ADDRESS_NOT_ASSIGNED	870
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_PREFIX_LEN	871
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_PREFIX_LEN	872
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_SUBNET_ADDRESS	873
#define RHP_LOG_ID_IKE_MOBIKE_I_ROUTABILITY_CHECK_TX_PROBE_2_V6	874
#define RHP_LOG_ID_REMOTE_CFG_SVR_ADDR_POOL_BAD_PREFIX_LEN	875
#define RHP_LOG_ID_RX_IKE_SA_INIT_N_FRAGMENTATION_SUPPORTED_PAYLOAD	876
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_FRAGMENTATION_PAYLOAD_ERR	877
#define RHP_LOG_ID_IKEV2_RETRANSMIT_REQ_NO_PACKET	879
#define RHP_LOG_ID_RX_INVALID_IKEV2_MESG_V6	880
#define RHP_LOG_ID_RX_IKEV2_VERIFY_DEFRAG_ERR	881
#define RHP_LOG_ID_RX_IKEV2_VERIFY_DEFRAG_ERR_V6	882
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_ERR	883
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_ERR_V6	884
#define RHP_LOG_ID_IKEV2_PARSE_RX_PAYLOAD_ERR_V6	885
#define RHP_LOG_ID_IKEV2_PARSE_RX_MESG_ERR_V6	886
#define RHP_LOG_ID_IKEV2_RX_REQ_FRAG_TIMEDOUT	887
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_PKT	888
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_PKT_V6	889
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_COMP_PKT	890
#define RHP_LOG_ID_RX_IKEV2_DEFRAG_COMP_PKT_V6	891
#define RHP_LOG_ID_IKE_MOBIKE_IF_STATE_CHANGED_BUT_IGNORED_0	892
#define RHP_LOG_ID_IKE_MOBIKE_R_NAT_T_DYN_DISABLED_USE_NON_NAT_T_PEER_PORT	893
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_UNKNOWN_PEER_LL_ADDR_NOTIFIED	894
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_ADDR_COLLISION	895
#define RHP_LOG_ID_RX_FIRST_UDP_ENCAP_ESP_PACKET	896
#define RHP_LOG_ID_RX_IKE_SA_INIT_RESP_PARSE_N_FRAGMENTATION_SUPPORTED_PAYLOAD_ERR	897
#define RHP_LOG_ID_MAIN_ENABLE_REALM	898
#define RHP_LOG_ID_MAIN_ENABLE_REALM_ERR	899
#define RHP_LOG_ID_MAIN_DISABLE_REALM	900
#define RHP_LOG_ID_MAIN_DISABLE_REALM_ERR	901
#define RHP_LOG_ID_UI_UPDATE_MY_KEY_INFO_NOT_EAP_SUP	902
#define RHP_LOG_ID_PARSE_ERR_XML_IPV4_ATTR	903
#define RHP_LOG_ID_PARSE_ERR_XML_BASE64_ATTR	904
#define RHP_LOG_ID_PARSE_ERR_XML_IPV4_SUBNET_ATTR	905
#define RHP_LOG_ID_PARSE_ERR_XML_DN_ATTR	906
#define RHP_LOG_ID_PARSE_ERR_XML_IPV6_ATTR	907
#define RHP_LOG_ID_PARSE_ERR_XML_IPV6_SUBNET_ATTR	908
#define RHP_LOG_ID_EVENT_LOG_SAVED_AS_TXT	909
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IF_NO_SAME_SUBNET_ADDR_USE_DEF	910
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IF_NO_SAME_SUBNET_ADDR	911
#define RHP_LOG_ID_DNS_PXY_FAILED_TO_ACTIVATE	912
#define RHP_LOG_ID_DNS_PXY_FAILED_TO_ACTIVATE_V6	913
#define RHP_LOG_ID_DNS_PXY_FAILED_TO_START	914
#define RHP_LOG_ID_IKE_SESS_RESUME_KEY	915
#define RHP_LOG_ID_IKE_SESS_RESUME_KEY_OLD	916
#define RHP_LOG_ID_RX_SESS_RESUME_REQ_PARSE_N_I_R_PAYLOAD_ERR	917
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_TICKET_OPAQUE_PAYLOAD_ERR	918
#define RHP_LOG_ID_RX_SESS_RESUME_REQ_PARSE_V_PAYLOAD_ERR	919
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_FRAGMENTATION_SUPPORTED_PAYLOAD_ERR	920
#define RHP_LOG_ID_RX_SESS_RESUME_REQ_ERR	921
#define RHP_LOG_ID_SESS_RESUME_TX_ERR_NOTIFY	922
#define RHP_LOG_ID_SESS_RESUME_TX_ERR_NOTIFY_FAILED	923
#define RHP_LOG_ID_RX_IKE_AUTH_INVALID_SESS_RESUME_ID_I	924
#define RHP_LOG_ID_RX_IKE_AUTH_INVALID_SESS_RESUME_ID_R	925
#define RHP_LOG_ID_RX_IKE_AUTH_INVALID_SESS_RESUME_ID_I	924
#define RHP_LOG_ID_RX_IKE_AUTH_INVALID_SESS_RESUME_ID_R	925
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_INVALID_SESS_RESUME_AUTH	926
#define RHP_LOG_ID_DBG_IKESA_SESS_RESUME_GENERATED_KEY_SKEYSEED	927
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_SESS_RESUME_OK	928
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_SESS_RESUME_ERR	929
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_SESS_RESUME_OK	930
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_SESS_RESUME_ERR	931
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_COOKIE_PAYLOAD_ERR	932
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_NO_N_COOKIE_PAYLOAD	933
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_INVALID_KE_PAYLOAD_ERR	934
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_N_ERR_PAYLOAD	935
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_ERR_PAYLOAD_ERR	936
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_SA_PAYLOAD_ERR	937
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_I_R_PAYLOAD_ERR	938
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_KE_PAYLOAD_ERR	939
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_CERTREQ_PAYLOAD_ERR	940
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_HTTP_CERT_LOOKUP_PAYLOAD_ERR	941
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_N_FRAGMENTATION_PAYLOAD_ERR	942
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PARSE_V_PAYLOAD_ERR	943
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_PRF_ALG_ERR	944
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_INTEG_ALG_ERR	945
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_ENCR_ALG_ERR	946
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_OK	947
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_ERR	948
#define RHP_LOG_ID_RX_SESS_RESUME_RESP_WAIT_RETRY	949
#define RHP_LOG_ID_IKE_AUTH_SESS_RESUME_NEW_REQ_PKT_ERR	950
#define RHP_LOG_ID_RX_IKE_AUTH_SESS_RESUME_REQ_OK	951
#define RHP_LOG_ID_RX_IKE_AUTH_SESS_RESUME_REQ_ERR	952
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_LT_OPAQUE_PAYLOAD	953
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_OPAQUE_PAYLOAD	954
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REQ_PAYLOAD	955
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_ENC_REQ_ERR	956
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_ENC_ERR	957
#define RHP_LOG_ID_TX_IKE_SESS_RESUME_TKT_LT_OPAQUE	958
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REQ_ERR	959
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REP_ERR	960
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REP	961
#define RHP_LOG_ID_IKEV2_TX_ALLOC_SESS_RESUME_REQ_ERR	962
#define RHP_LOG_ID_IKEV2_SESS_RESUME_DEC_RX_INVALID_TKT	963
#define RHP_LOG_ID_IKEV2_SESS_RESUME_TX_ALLOC_REP_ERR	964
#define RHP_LOG_ID_IKEV2_SESS_RESUME_DEC_TKT_OK	965
#define RHP_LOG_ID_IKEV2_SESS_RESUME_DEC_TKT_ERR	966
#define RHP_LOG_ID_IKEV2_TX_ALLOC_IKE_SA_INIT_REQ_ERR	967
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REP_TKT_LT_OPAQUE_PAYLOAD	968
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REP_TKT_OPAQUE_PAYLOAD	969
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REQ_TKT_OPAQUE_PAYLOAD	970
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REQ_TKT_OPAQUE_PAYLOAD_ERR	971
#define RHP_LOG_ID_RX_SESS_RESUME_REQ_PARSE_N_TICKET_OPAQUE_PAYLOAD_ERR	972
#define RHP_LOG_ID_EXEC_AUTO_RECONNECT_BY_SESS_RESUME	973
#define RHP_LOG_ID_IKEV2_RX_NEW_SESS_RESUME_REQ	974
#define RHP_LOG_ID_IKE_SESS_RESUME_KEY_UPDATED	975
#define RHP_LOG_ID_IKE_SESS_RESUME_KEY_UPDATED_OLD_KEY	976
#define RHP_LOG_ID_IKE_SESS_RESUME_KEY_UPDATED_ERR	977
#define RHP_LOG_ID_IKE_SESS_RESUME_DEC_TKT_ERR	978
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REP_TKT_LT_OPAQUE_PLD_DATA	979
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_REP_TKT_OPAQUE_PLD_DATA	980
#define RHP_LOG_ID_TX_IKE_SESS_RESUME_TKT_LT_OPAQUE_DATA	981
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN	982
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_ENC	983
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_ERR	984
#define RHP_LOG_ID_IKEV2_SESS_RESUME_REACHED_MAX_REVOKED_TKTS	985
#define RHP_LOG_ID_IKEV2_SESS_RESUME_RX_REVOKED_TKT_ERR	986
#define RHP_LOG_ID_PROTECTED_PROCESS_START	987
#define RHP_LOG_ID_MAIN_PROCESS_START	988
#define RHP_LOG_ID_RESET_IKEV2_QCD_KEY	989
#define RHP_LOG_ID_RESET_IKEV2_QCD_KEY_ERR	990
#define RHP_LOG_ID_RESET_IKEV2_SESS_RESUME_KEY	991
#define RHP_LOG_ID_RESET_IKEV2_SESS_RESUME_KEY_ERR	992
#define RHP_LOG_ID_AUTO_RECONNECT_I_SESS_RESUME_TKT_EXPIRED	993
#define RHP_LOG_ID_IKE_SESS_RESUME_I_TX_NEW_TKT_REQ	994
#define RHP_LOG_ID_IKE_SESS_RESUME_I_TX_NEW_TKT_REQ_ERR	995
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REQ_I_ERR	996
#define RHP_LOG_ID_RX_IKE_SESS_RESUME_TKT_REQ_I	997
#define RHP_LOG_ID_IKE_QCD_TX_REKEYED_QCD_TKN	998
#define RHP_LOG_ID_IKE_QCD_TX_REKEYED_QCD_TKN_ERR	999
#define RHP_LOG_ID_IKE_TX_NEW_REQ	1000
#define RHP_LOG_ID_IKE_TX_NEW_REQ_ERR	1001
#define RHP_LOG_ID_IKE_SESS_RESUME_I_TICKET_INFO	1002
#define RHP_LOG_ID_IKE_SESS_RESUME_I_TICKET_INFO_2	1003
#define RHP_LOG_ID_ALWAYS_ON_CONNECT_EAP_KEY_NOT_SAVED	1004
#define RHP_LOG_ID_EXEC_AUTO_RECONNECT_IKESA_ALREADY_EXISTS	1005
#define RHP_LOG_ID_EXEC_AUTO_RECONNECT_EAP_KEY_NOT_CACHED	1006
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_INVALID_NULL_ID_I_AUTH	1007
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_INVALID_NULL_ID_R_AUTH	1008
#define RHP_LOG_ID_VERIFY_PSK_NOT_ALLOWED	1009
#define RHP_LOG_ID_VERIFY_EAP_SUP__NOT_ALLOWED	1010
#define RHP_LOG_ID_VERIFY_RSASIG_NOT_ALLOWED	1011
#define RHP_LOG_ID_RX_IKE_AUTH_RESP_AUTH_PAYLOAD_NOT_ALLOWED_AUTH_METHOD_ERR	1012
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_UNSUP_AUTH_METHOD	1013
#define RHP_LOG_ID_REMOTE_PEER_ADDRESS_NOT_SPECIFIED_FOR_NULL_ID	1014
#define RHP_LOG_ID_NULL_AUTH_NOT_ALLOWED	1015
#define RHP_LOG_ID_RX_CFG_REQ_IPV6_AUTOCONF	1016
#define RHP_LOG_ID_RX_CFG_REQ_REJECT_NON_CLIENT	1017
#define RHP_LOG_ID_RX_CFG_REQ_IPV6_AUTOCONF_ALLOWED	1018
#define RHP_LOG_ID_RX_CFG_REQ_CLIENT_ANY_TS_NOT_ALLOWED	1019
#define RHP_LOG_ID_IKE_INTERNAL_NET_IF_STATE_CHANGED_BUT_IGNORED_0	1020
#define RHP_LOG_ID_IKE_INTERNAL_NET_IF_STATE_CHANGED_PENDING	1021
#define RHP_LOG_ID_IKE_INTERNAL_NET_IF_STATE_CHANGED	1022
#define RHP_LOG_ID_IKE_INTERNAL_NET_IF_STATE_CHANGED_ERR	1023
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_NEW_PEER_ADDR_NOTIFIED	1024
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_NEW_PEER_LL_ADDR_NOTIFIED	1025
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_MAC_COLLISION	1026
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_PEER_ADDR_CLEARED	1027
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_PEER_ADDR_UPDATED	1028
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_PEER_MAC_UPDATED	1029
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_IPV6_AUTOCONF_EXEC_REKEY	1030
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_IPV6_AUTOCONF_TX_UPDATED_ADDR_V4	1031
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_IPV6_AUTOCONF_TX_UPDATED_ADDR_V6	1032
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_IPV6_AUTOCONF_UPDATED_ADDR_IGNORED	1033
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_IPV6_AUTOCONF_NO_CHILDSA_FOUND	1034
#define RHP_LOG_ID_RX_IKE_INTERNAL_NET_INFO_REQ_ADDR_RESERVED	1035
#define RHP_LOG_ID_REKEYED_CHILDSA_RX_IPV6_AUTOCONF_REKEY_SA	1036
#define RHP_LOG_ID_REKEYED_CHILDSA_RX_IPV6_AUTOCONF_REKEY_SA_BUT_NOT_ENABLED	1037
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_RADIUS_DISABLED	1038
#define RHP_LOG_ID_IKE_AUTH_RADIUS_PEER_NOTIFIED_REALM_NOT_MATCH	1039
#define RHP_LOG_ID_IKE_AUTH_PEER_NOTIFIED_REALM_NOT_MATCH	1040
#define RHP_LOG_ID_IKE_AUTH_RADIUS_REALM_NOT_FOUND	1041
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SECRET	1042
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SECRET_ERR	1043
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SYSPXY_CFG	1044
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SYSPXY_CFG_ERR	1045
#define RHP_LOG_ID_RADIUS_NO_SHARED_SECRET_CONFIGURED	1046
#define RHP_LOG_ID_RADIUS_TX_ACCESS_REQUEST	1047
#define RHP_LOG_ID_RADIUS_TX_ACCESS_REQUEST_ERR	1048
#define RHP_LOG_ID_RADIUS_TX_ACCESS_REQUEST_SIGN_ERR	1049
#define RHP_LOG_ID_RADIUS_RX_MESG	1050
#define RHP_LOG_ID_RADIUS_RX_MESG_AUTH_ERR	1051
#define RHP_LOG_ID_RADIUS_RX_MESG_AUTH_ERR_2	1052
#define RHP_LOG_ID_RADIUS_OPEN_SOCKET_ERR	1053
#define RHP_LOG_ID_RADIUS_ATTR_CONNECT_INFO_TX	1054
#define RHP_LOG_ID_RADIUS_ATTR_NAS_PORT_TYPE_TX	1055
#define RHP_LOG_ID_RADIUS_ATTR_FRAMED_MTU_TX	1056
#define RHP_LOG_ID_RADIUS_ATTR_CALLING_STATION_ID_TX	1057
#define RHP_LOG_ID_RADIUS_ATTR_NAS_IP_ADDRESS_TX	1058
#define RHP_LOG_ID_RADIUS_ATTR_NAS_IPV6_ADDRESS_TX	1059
#define RHP_LOG_ID_RADIUS_ATTR_NAS_ID_TX	1060
#define RHP_LOG_ID_RADIUS_ATTR_USER_NAME_TX	1061
#define RHP_LOG_ID_RADIUS_ATTR_STATE_TX	1062
#define RHP_LOG_ID_RADIUS_ALLOC_TX_MESG	1063
#define RHP_LOG_ID_RADIUS_ATTR_EAP_TX	1064
#define RHP_LOG_ID_RADIUS_RX_ATTR_EAP_IDENTITY	1065
#define RHP_LOG_ID_RADIUS_RX_ATTR_EAP_REQ	1066
#define RHP_LOG_ID_RADIUS_RX_ATTR_EAP_SUCCESS_OR_FAILURE	1067
#define RHP_LOG_ID_RADIUS_RX_ATTR_EAP_UNKNOWN_CODE	1068
#define RHP_LOG_ID_RADIUS_RX_ATTR_VENDOR_SPECIFIC_MS_IPV4	1069
#define RHP_LOG_ID_RADIUS_RX_ATTR_VENDOR_SPECIFIC_MS_INVALID_IPV4	1070
#define RHP_LOG_ID_RADIUS_RX_ATTR_VENDOR_SPECIFIC_MS	1071
#define RHP_LOG_ID_RADIUS_RX_ATTR_VENDOR_SPECIFIC	1072
#define RHP_LOG_ID_RADIUS_RX_ATTR_IPV4	1073
#define RHP_LOG_ID_RADIUS_RX_ATTR_INVALID_IPV4	1074
#define RHP_LOG_ID_RADIUS_RX_ATTR_IPV6	1075
#define RHP_LOG_ID_RADIUS_RX_ATTR_INVALID_IPV6	1076
#define RHP_LOG_ID_RADIUS_RX_ATTR_STRING	1077
#define RHP_LOG_ID_RADIUS_RX_ATTR_UINT32	1078
#define RHP_LOG_ID_RADIUS_RX_ATTR_INVALID_UINT32	1079
#define RHP_LOG_ID_RADIUS_RX_ATTR_BIN	1080
#define RHP_LOG_ID_RADIUS_ATTR_EAP_IDENTITY_TX	1081
#define RHP_LOG_ID_EAP_LOCAL_AUTH_IS_ENABLED	1082
#define RHP_LOG_ID_EAP_RADIUS_AUTH_IS_ENABLED	1083
#define RHP_LOG_ID_RADIUS_RETRANSMIT_ACCESS_REQUEST	1084
#define RHP_LOG_ID_RADIUS_RETRANSMIT_ACCESS_REQUEST_ERR	1085
#define RHP_LOG_ID_RADIUS_AUTH_REJECTED	1086
#define RHP_LOG_ID_RADIUS_AUTH_ACCEPTED_MSK_INFO	1087
#define RHP_LOG_ID_RADIUS_AUTH_ACCEPTED_NO_MSK_FOUND	1088
#define RHP_LOG_ID_RADIUS_AUTH_ACCEPTED_NO_USER_NAME_FOUND	1089
#define RHP_LOG_ID_RADIUS_AUTH_ACCEPTED	1090
#define RHP_LOG_ID_RADIUS_RX_MESG_ERROR	1091
#define RHP_LOG_ID_RADIUS_RX_MESG_ERROR_2	1092
#define RHP_LOG_ID_RADIUS_RX_MESG_IGNORED	1093
#define RHP_LOG_ID_RADIUS_ERROR	1094
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_VERIFY_AUTHENTICATOR_ERR	1095
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_VERIFY_MESG_AUTHENTICATOR_ERR	1096
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_MS_MPPE_KEY_ATTR_ERR	1097
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_PRIVATE_REALM_ID_ATTR_ERR	1098
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_PRIVATE_REALM_ROLE_ATTR_ERR	1099
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_REALM_ID	1100
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_REALM_ID_ERR	1101
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_VPN_REALM_ROLES	1102
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_VPN_REALM_ROLES_ERR	1103
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_VERIFY_ERR	1104
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_RX_MESG_ERR	1105
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_MS_MPPE_KEYS_ERR	1106
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_MS_MPPE_KEYS_INFO	1107
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_MSK	1108
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_MSK_NOT_GENERATED	1109
#define RHP_LOG_ID_RADIUS_RX_ATTR_PRIVATE_ATTR	1110
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_MS_MPPE_SEND_KEY	1111
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_MS_MPPE_RECV_KEY	1112
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_ROLE_STRING	1113
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_REALM_ID	1114
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_REALM_ID_NOT_REBOUND	1115
#define RHP_LOG_ID_RADIUS_RX_ATTR_ERROR_CAUSE	1116
#define RHP_LOG_ID_RADIUS_RX_ATTR_INVALID_ERROR_CAUSE	1117
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_ADDRESS_BY_RADIUS_PRIV_INTERNAL_ADDR_ATTR	1118
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_ADDRESS_BY_RADIUS_FRAMED_IPV4_ATTR	1119
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_ADDRESS_BY_RADIUS_PRIV_INTERNAL_ADDR_ATTR	1120
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_ADDRESS_BY_RADIUS_FRAMED_IPV6_ATTR	1121
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_DNS_SERVER_BY_RADIUS_PRIV_DNS_SERVER_ATTR	1122
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_DNS_SERVER_BY_RADIUS_MS_PRIMARY_DNS_SERVER_ATTR	1123
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_DNS_SERVER_BY_RADIUS_PRIV_DNS_SERVER_ATTR	1124
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_DNS_SERVER_BY_RADIUS_DNS_IPV6_SERVER_ATTR	1125
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_SUBNET_BY_RADIUS_PRIV_INTERNAL_ROUTE_ATTR	1126
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_GATEWAY_BY_RADIUS_PRIV_GATEWAY_ATTR	1127
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_SUBNET_BY_RADIUS_PRIV_INTERNAL_ROUTE_ATTR	1128
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV6_GATEWAY_BY_RADIUS_GATEWAY_ATTR	1129
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_IPV4_WINS_BY_RADIUS_MS_PRIMARY_NBNS_SERVER_ATTR	1130
#define RHP_LOG_ID_RX_CFG_REQ_INTERNAL_DNS_SUFFIX_BY_RADIUS_PRIV_DOMAIN_NAME_ATTR	1131
#define RHP_LOG_ID_RADIUS_SYSPXY_AUTH_PARSE_PRIVATE_ATTR_COMMON_ERR	1132
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN_RADIUS_TKT	1133
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN_RADIUS_TKT_ATTR_STR	1134
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN_RADIUS_TKT_ATTR_IPV4	1135
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN_RADIUS_TKT_ATTR_IPV6	1136
#define RHP_LOG_ID_IKE_SESS_RESUME_TKT_DUMP_PLAIN_RADIUS_TKT_ATTR_BIN	1137
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_VPN_REALM_ROLES_FOR_NOT_PROTECTED_EAP_ID	1138
#define RHP_LOG_ID_RADIUS_SYSPXY_VERIFY_RX_VPN_REALM_ROLES_FOR_NOT_PROTECTED_EAP_ID_ERR	1139
#define RHP_LOG_ID_INVALIDATE_SESS_RESUME_TKTS	1140
#define RHP_LOG_ID_RADIUS_RESOLVE_SERVER_ADDR	1141
#define RHP_LOG_ID_RADIUS_RESOLVE_SERVER_ADDR_ERR	1142
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SECRET_FOR_SECONDARY_SERVER_ERR	1143
#define RHP_LOG_ID_UI_UPDATE_RADIUS_SECRET_FOR_SECONDARY_SERVER	1144
#define RHP_LOG_ID_RADIUS_ATTR_ACCT_SESSION_ID_TX	1145
#define RHP_LOG_ID_UI_UPDATE_RADIUS_ACCT_SECRET_ERR	1146
#define RHP_LOG_ID_UI_UPDATE_RADIUS_ACCT_SECRET	1147
#define RHP_LOG_ID_UI_UPDATE_RADIUS_ACCT_SECRET_FOR_SECONDARY_SERVER_ERR	1148
#define RHP_LOG_ID_UI_UPDATE_RADIUS_ACCT_SECRET_FOR_SECONDARY_SERVER	1149
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_USER_NAME_IKEV2_ID_TX	1150
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_USER_NAME_EAP_ID_TX	1151
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_NAS_ID_TX	1152
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_NAS_ID_IKEV2_ID_TX	1153
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_CALLING_STATION_ID_TX	1154
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_STATUS_TYPE_TX	1155
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_SESSION_ID_TX	1156
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_AUTHENTIC_TX	1157
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_TERMINATE_CAUSE_TX	1158
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_SESSION_TIME_TX	1159
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_INPUT_OCTETS_TX	1160
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_OUTPUT_OCTETS_TX	1161
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_INPUT_PACKETS_TX	1162
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_OUTPUT_PACKETS_TX	1163
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_CONNECT_INFO_TX	1164
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_NAS_PORT_TYPE_TX	1165
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_NAS_IP_ADDRESS_TX	1166
#define RHP_LOG_ID_RADIUS_ACCT_ATTR_NAS_IPV6_ADDRESS_TX	1167
#define RHP_LOG_ID_RADIUS_OPEN_SOCKET	1168
#define RHP_LOG_ID_CREATED_CHILDSA_RESPONDER_ENCAP_MODE_NOT_MATCHED	1169
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_DMVPN_A	1170
#define RHP_LOG_ID_DBG_IKESA_GENERATED_KEY_VALUES_SK_DMVPN_E	1171
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_DMVPN_A	1172
#define RHP_LOG_ID_DBG_IKESA_GENERATED_NEW_KEY_VALUES_SK_DMVPN_E	1173
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_DMVPN_A	1174
#define RHP_LOG_ID_DBG_IKESA_GENERATED_OLD_KEY_VALUES_SK_DMVPN_E	1175
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_SUPPORTED_NOTIFY	1176
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_TX_SUPPORTED_NOTIFY	1177
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_AUTH_PEER_DISABLED	1178
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_AUTH_ENABLED	1179
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_AUTH_REQ_ERR	1180
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_REQ_ERR	1181
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_REP_ERR	1182
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_AUTH_REP_ERR	1183
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_AUTH_TKT_NOTIFY	1184
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_ENC_AUTH_TKT_NOTIFY	1185
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_INFO_REP	1186
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_INFO_REP_ERR	1187
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_INFO_REQ	1188
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_RX_INFO_REQ_ERR	1189
#define RHP_LOG_ID_IKE_AUTH_TKT_HUB2SPOKE_TX_ERR_NOTIFY	1190
#define RHP_LOG_ID_NHRP_REQ_SESS_TIMER_ERR	1191
#define RHP_LOG_ID_NHRP_REQ_SESS_TIMER_REGISTRATION_REQ_RETRY_FAILED	1192
#define RHP_LOG_ID_NHRP_REQ_SESS_START	1193
#define RHP_LOG_ID_NHRP_REQ_SESS_START_ERR	1194
#define RHP_LOG_ID_NHRP_TX_REGISTRATION_REQ_MESG	1195
#define RHP_LOG_ID_NHRP_TX_REGISTRATION_REQ_ERR	1196
#define RHP_LOG_ID_NHRP_TX_TRAFFIC_INDICATION_MESG	1197
#define RHP_LOG_ID_NHRP_TX_TRAFFIC_INDICATION_MESG_ERR	1198
#define RHP_LOG_ID_NHRP_CACHE_DELETE	1199
#define RHP_LOG_ID_NHRP_CACHE_PUT	1200
#define RHP_LOG_ID_NHRP_TX_REGISTRATION_REP	1201
#define RHP_LOG_ID_NHRP_TX_PURGE_REP	1202
#define RHP_LOG_ID_NHRP_TX_PURGE_REP_ERR	1203
#define RHP_LOG_ID_NHRP_RX_PURGE_REQ	1204
#define RHP_LOG_ID_NHRP_RX_PURGE_REQ_ERR	1205
#define RHP_LOG_ID_NHRP_RX_PURGE_REP	1206
#define RHP_LOG_ID_NHRP_RX_PURGE_REP_ERR	1207
#define RHP_LOG_ID_NHRP_TX_RESOLUTION_REP	1208
#define RHP_LOG_ID_NHRP_TX_RESOLUTION_REP_ERR	1209
#define RHP_LOG_ID_NHRP_CONNECT_SHORTCUT	1210
#define RHP_LOG_ID_NHRP_CONNECT_SHORTCUT_ERR	1211
#define RHP_LOG_ID_NHRP_FWD_RESOLUTION_REQ	1212
#define RHP_LOG_ID_NHRP_FWD_RESOLUTION_REQ_ERR	1213
#define RHP_LOG_ID_NHRP_RX_RESOLUTION_REQ	1214
#define RHP_LOG_ID_NHRP_RX_RESOLUTION_REP	1215
#define RHP_LOG_ID_NHRP_RX_RESOLUTION_REP_ERR	1216
#define RHP_LOG_ID_NHRP_FWD_RESOLUTION_REP	1217
#define RHP_LOG_ID_NHRP_FWD_RESOLUTION_REP_ERR	1218
#define RHP_LOG_ID_NHRP_RX_TRAFFIC_INDICATION	1219
#define RHP_LOG_ID_NHRP_RX_TRAFFIC_INDICATION_ERR	1220
#define RHP_LOG_ID_NHRP_UPDATE_ADDR	1221
#define RHP_LOG_ID_NHRP_UPDATE_ADDR_ERR	1222
#define RHP_LOG_ID_NHRP_TX_RESOLUTION_REQ	1223
#define RHP_LOG_ID_NHRP_RX_RESOLUTION_REQ_ERR	1224
#define RHP_LOG_ID_VERIFY_AUTH_TKT_NOT_ALLOWED	1225
#define RHP_LOG_ID_AUTH_TKT_INVALID_PEER_SESSION_KEY	1226
#define RHP_LOG_ID_RX_IKE_AUTH_PARSE_N_ENC_AUTH_TKT_PAYLOAD	1227
#define RHP_LOG_ID_RX_IKE_AUTH_REQ_PARSE_N_ENC_AUTH_TKT_PAYLOAD_ERR	1228
#define RHP_LOG_ID_VERIFY_PSK_AUTH_TKT_REALM_NOT_MATCHED	1229
#define RHP_LOG_ID_IKEV1_TX_ERR_NOTIFY	1230
#define RHP_LOG_ID_IKEV1_RX_ERR_NOTIFY	1231
#define RHP_LOG_ID_IKEV1_TX_MESG_ERR	1232
#define RHP_LOG_ID_IKEV1_RX_MESG_ERR	1233
#define RHP_LOG_ID_RX_INVALID_IKEV1_MESG	1234
#define RHP_LOG_ID_RX_INVALID_IKEV1_MESG_V6	1235
#define RHP_LOG_ID_IKEV1_RX_NEW_MAIN_MODE_REQ	1236
#define RHP_LOG_ID_IKEV1_RX_NEW_AGGRESSIVE_MODE_REQ	1237
#define RHP_LOG_ID_IKEV1_PARSE_RX_PAYLOAD_ERR	1238
#define RHP_LOG_ID_IKEV1_PARSE_RX_PAYLOAD_ERR_V6	1239
#define RHP_LOG_ID_IKEV1_PARSE_RX_MESG_ERR	1240
#define RHP_LOG_ID_IKEV1_PARSE_RX_MESG_ERR_V6	1241
#define RHP_LOG_ID_IKEV1_TX_ALLOC_MAIN_REQ_ERR	1242
#define RHP_LOG_ID_RX_IKEV1_MAIN_REQ_PARSE_SA_PAYLOAD_ERR	1243
#define RHP_LOG_ID_RX_IKEV1_MAIN_REQ_PARSE_V_PAYLOAD_ERR	1244
#define RHP_LOG_ID_RX_IKEV1_MAIN_REQ_OK	1245
#define RHP_LOG_ID_RX_IKEV1_MAIN_REQ_ERR	1246
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_PARSE_SA_PAYLOAD_ERR	1247
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_PARSE_V_PAYLOAD_ERR	1248
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_PRF_ALG_ERR	1249
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_ENCR_ALG_ERR	1250
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_OK	1251
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_ERR	1252
#define RHP_LOG_ID_RX_IKEV1_MAIN_PARSE_SA_PAYLOAD	1253
#define RHP_LOG_ID_RX_IKEV1_MAIN_REQ_NO_DEF_IKEV1_REALM_FOUND	1254
#define RHP_LOG_ID_RX_IKEV1_MAIN_RESP_HASH_ALG_ERR	1255
#define RHP_LOG_ID_IKEV1_RETRANSMIT_ERR	1256
#define RHP_LOG_ID_IKEV1_RETRANSMIT_MESG_ERR	1257
#define RHP_LOG_ID_IKEV1_RETRANSMIT_MESG_V6_ERR	1258
#define RHP_LOG_ID_IKEV1_EXEC_RETRANSMIT	1259
#define RHP_LOG_ID_IKEV1_EXEC_RETRANSMIT_V6	1260
#define RHP_LOG_ID_IKEV1_RETRANSMIT_MESG_NO_PACKET	1261
#define RHP_LOG_ID_IKEV1_RETRANSMIT_RESPONSE	1262
#define RHP_LOG_ID_IKEV1_RETRANSMIT_RESPONSE_V6	1263
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_1_PARSE_SA_PAYLOAD_ERR	1264
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_1_PARSE_V_PAYLOAD_ERR	1265
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_1_OK	1266
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_1_ERR	1267
#define RHP_LOG_ID_RX_IKEV1_PARSE_KE_PAYLOAD	1268
#define RHP_LOG_ID_RX_IKEV1_PARSE_NONCE_PAYLOAD	1269
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_2_PARSE_N_I_R_PAYLOAD_ERR	1270
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_2_PARSE_KE_PAYLOAD_ERR	1271
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_2_OK	1272
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_2_ERR	1273
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_PARSE_N_I_R_PAYLOAD_ERR	1274
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_PARSE_KE_PAYLOAD_ERR	1275
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_ERR	1276
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_OK	1277
#define RHP_LOG_ID_RX_IKEV1_MAIN_SKEYID_ERR	1278
#define RHP_LOG_ID_IKEV1_VERIFY_PSK_RX_INVALID_PEER_ID_TYPE	1279
#define RHP_LOG_ID_IKEV1_VERIFY_PSK_REALM_NOT_DEFINED	1280
#define RHP_LOG_ID_IKEV1_VERIFY_PSK_NOT_ALLOWED	1281
#define RHP_LOG_ID_IKEV1_NO_PEER_PSK_FOUND	1282
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_2_PARSE_NONCE_PAYLOAD_ERR	1283
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PARSE_HASH_PAYLOAD_ERR	1284
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PARSE_ID_PAYLOAD_ERR	1285
#define RHP_LOG_ID_RX_IKEV1_PARSE_HASH_PAYLOAD	1286
#define RHP_LOG_ID_RX_IKEV1_PARSE_ID_PAYLOAD	1287
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_IKE_PKT_VIA_UNCONFIGURED_IF	1288
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_OK	1289
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_ERR	1290
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_3_OK	1291
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_3_ERR	1292
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_1_ENCAP_MODE_NOT_MATCHED	1293
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_1	1294
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_1_TX_ERR_NOTIFY	1295
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_1_ERR	1296
#define RHP_LOG_ID_IKEV1_RX_QUICK_I_1	1297
#define RHP_LOG_ID_IKEV1_RX_QUICK_I_1_ERR	1298
#define RHP_LOG_ID_CREATED_IPSECSA_INITIATOR	1299
#define RHP_LOG_ID_CREATED_IPSECSA_RESPONDER	1300
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_2_ERR	1301
#define RHP_LOG_ID_RX_IKEV1_DELETE_IKESA_REQ	1302
#define RHP_LOG_ID_RX_IKEV1_DELETE_IKESA_REQ_IGNORED	1303
#define RHP_LOG_ID_RX_IKEV1_DELETE_IKESA_REQ_ERR	1304
#define RHP_LOG_ID_RX_IKEV1_DELETE_IPSECSA_REQ_NOT_FOUND	1305
#define RHP_LOG_ID_RX_IKEV1_DELETE_IPSECSA_REQ	1306
#define RHP_LOG_ID_RX_IKEV1_DELETE_IPSECSA_REQ_ERR	1307
#define RHP_LOG_ID_RX_IKEV1_NAT_T_REQ_PARSE_VID_PAYLOAD_ERR	1308
#define RHP_LOG_ID_RX_IKEV1_NAT_T_REQ_PEER_NAT_T_SUPPORTED	1309
#define RHP_LOG_ID_RX_IKEV1_NAT_T_REQ_VID_ERR	1310
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_1_OK	1311
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_1_ERR	1312
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_1_ERR_2	1313
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_PARSE_SA_PAYLOAD_ERR	1314
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_2_PARSE_V_PAYLOAD_ERR	1315
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PARSE_NONCE_PAYLOAD_ERR	1316
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PARSE_KE_PAYLOAD_ERR	1317
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_RSASIG_OK	1318
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_OK	1319
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_PARSE_N_I_R_PAYLOAD_ERR	1320
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_PARSE_KE_PAYLOAD_ERR	1321
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_ERR	1322
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_PSK_PARSE_HASH_PAYLOAD_ERR	1323
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_PSK_PARSE_ID_PAYLOAD_ERR	1324
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_PSK_OK	1325
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_PSK_ERR	1326
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_PARSE_HASH_PAYLOAD_ERR	1327
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_PARSE_ID_PAYLOAD_ERR	1328
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_IKE_PKT_VIA_UNCONFIGURED_IF	1329
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_OK	1330
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_ERR	1331
#define RHP_LOG_ID_IKEV1_RX_QUICK_I_2_ERR	1332
#define RHP_LOG_ID_IKEV1_RX_QUICK_R_3_ERR	1333
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_R_3_NO_NAT	1334
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_R_3_PEER_BEHIND_A_NAT	1335
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_R_3_LOCAL_BEHIND_A_NAT	1336
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_R_3_ERR	1337
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_I_4_NO_NAT	1338
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_I_4_PEER_BEHIND_A_NAT	1339
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_I_4_LOCAL_BEHIND_A_NAT	1340
#define RHP_LOG_ID_RX_IKEV1_MAIN_NATT_I_4_ERR	1341
#define RHP_LOG_ID_IKEV1_TRY_SECONDARY_ROUTE	1342
#define RHP_LOG_ID_IKEV1_TRY_SECONDARY_ROUTE_V6	1343
#define RHP_LOG_ID_IKEV1_TRY_SECONDARY_ROUTE_ERR	1344
#define RHP_LOG_ID_IKEV1_TRY_SECONDARY_ROUTE_V6_ERR	1345
#define RHP_LOG_ID_RX_IKEV1_DPD_REQ_PARSE_VID_PAYLOAD_ERR	1346
#define RHP_LOG_ID_RX_IKEV1_DPD_PEER_SUPPORTED	1347
#define RHP_LOG_ID_RX_IKEV1_DPD_VID_ERR	1348
#define RHP_LOG_ID_IKEV1_RX_QUICK_I_4_ERR	1349
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_PARSE_N_PAYLOADS_ERR	1350
#define RHP_LOG_ID_RX_IKEV1_PARSE_CERT_REQ_PAYLOAD_UNSUP_CERT_ENCODING	1351
#define RHP_LOG_ID_RX_IKEV1_PARSE_CERT_REQ_PAYLOAD_INVALID_CA_DN_DER	1352
#define RHP_LOG_ID_RX_IKEV1_PARSE_CERT_REQ_PAYLOAD_MAX_CA_DN_DATA_REACHED	1353
#define RHP_LOG_ID_RX_IKEV1_PARSE_CERT_REQ_PAYLOAD	1354
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PARSE_CERT_REQ_PAYLOAD_ERR	1355
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_PSK_INVALID_HASH_PAYLOAD_VALUE	1356
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PSK_INVALID_HASH_PAYLOAD_VALUE	1357
#define RHP_LOG_ID_MY_ID_NOT_RESOLVED	1358
#define RHP_LOG_ID_RX_IKEV1_MAIN_RSASIG_SIGN_ERR	1359
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_PARSE_CERT_REQ_PAYLOAD_ERR	1360
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_HASH_PAYLOAD_ERR	1361
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_ID_PAYLOAD_ERR	1362
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_CERT_PAYLOAD_ERR	1363
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_N_PAYLOADS_ERR	1364
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_N_REALM_ID_PAYLOAD_ERR	1365
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_ERR	1366
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_PARSE_HASH_PAYLOAD_ERR	1367
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_PARSE_ID_PAYLOAD_ERR	1368
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_PARSE_CERT_PAYLOAD_ERR	1369
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_ERR	1370
#define RHP_LOG_ID_RX_IKEV1_MAIN_RSASIG_VERIFY_ERR	1371
#define RHP_LOG_ID_RX_IKEV1_MAIN_RSASIG_VERIFY_AND_SIGN_ERR	1372
#define RHP_LOG_ID_RX_IKEV1_MAIN_RSASIG_SIGN_ERR_TX_ERR_NOTIFY	1373
#define RHP_LOG_ID_RX_IKEV1_MAIN_RSASIG_VERIFY_ERR_TX_ERR_NOTIFY	1374
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_PSK_OK	1375
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_3_PSK_OK	1376
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_RSASIG_OK	1377
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_OK	1378
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_OK	1379
#define RHP_LOG_ID_IKEV1_RX_VERIFY_REQ_ERR	1380
#define RHP_LOG_ID_IKEV1_RX_VERIFY_REQ_V6_ERR	1381
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_6_RSASIG_ID_PAYLOAD_INVALID_PEER_ID	1382
#define RHP_LOG_ID_IKEV1_TX_ALLOC_AGGRESSIVE_REQ_ERR	1383
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_CHECK_PAYLOADS_ERR	1384
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_CHECK_PAYLOADS_ERR	1385
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_CHECK_PAYLOADS_ERR_2	1386
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_N_REALM_ID_PAYLOAD_ERR	1387
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_ERR	1388
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_SA_PAYLOAD_ERR	1389
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_V_PAYLOAD_ERR	1390
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_NONCE_PAYLOAD_ERR	1391
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_KE_PAYLOAD_ERR	1392
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_ID_PAYLOAD_ERR	1393
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_PARSE_CERT_REQ_PAYLOAD_ERR	1394
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_IKE_PKT_VIA_UNCONFIGURED_IF	1395
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_ERR_2	1396
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_RESOLVE_REALM_OK	1397
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_1_RESOLVE_REALM_ERR	1398
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_SKEYID_ERR	1399
#define RHP_LOG_ID_RESOLVE_AUTH_REALM_RX_INVALID_PEER_ID_TYPE	1400
#define RHP_LOG_ID_RESOLVE_AUTH_REALM_NOT_DEFINED	1401
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_SA_PAYLOAD_ERR	1402
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_NONCE_PAYLOAD_ERR	1403
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_KE_PAYLOAD_ERR	1404
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_CERT_REQ_PAYLOAD_ERR	1405
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_RSASIG_PARSE_HASH_PAYLOAD_ERR	1406
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_RSASIG_PARSE_CERT_PAYLOAD_ERR	1407
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_HASH_PAYLOAD_ERR	1408
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_ID_PAYLOAD_ERR	1409
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_ID_PAYLOAD_INVALID_PEER_ID	1410
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PARSE_V_PAYLOAD_ERR	1411
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_OK	1412
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_ERR	1413
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_2_PSK_INVALID_HASH_PAYLOAD_VALUE	1414
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_PARSE_HASH_PAYLOAD_ERR	1415
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_PARSE_N_PAYLOADS_ERR	1416
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_INVALID_HASH_PAYLOAD_VALUE	1417
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_IKE_PKT_VIA_UNCONFIGURED_IF	1418
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_OK	1419
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_PSK_ERR	1420
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_2_RSASIG_OK	1421
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_RSASIG_SIGN_ERR	1422
#define RHP_LOG_ID_RX_IKEV1_MAIN_I_4_PARSE_NONCE_PAYLOAD_ERR	1423
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_I_3_RSASIG_OK	1424
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_RSASIG_VERIFY_ERR	1425
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_RSASIG_VERIFY_AND_SIGN_ERR	1426
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_RSASIG_PARSE_HASH_PAYLOAD_ERR	1427
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_RSASIG_PARSE_CERT_PAYLOAD_ERR	1428
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_RSASIG_PARSE_N_PAYLOADS_ERR	1429
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_RSASIG_ERR	1430
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_R_3_RSASIG_OK	1431
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_I_2_NO_NAT	1432
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_I_2_PEER_BEHIND_A_NAT	1433
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_I_2_LOCAL_BEHIND_A_NAT	1434
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_I_2_ERR	1435
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_R_3_NO_NAT	1436
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_R_3_PEER_BEHIND_A_NAT	1437
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_R_3_LOCAL_BEHIND_A_NAT	1438
#define RHP_LOG_ID_RX_IKEV1_AGGRESSIVE_NATT_R_3_ERR	1439
#define RHP_LOG_ID_XAUTH_NOT_AUTHENTICATOR	1440
#define RHP_LOG_ID_XAUTH_PAP_AUTH_OK	1441
#define RHP_LOG_ID_XAUTH_PAP_AUTH_FAILED	1442
#define RHP_LOG_ID_XAUTH_ACTUAL_REALM_FOUND	1443
#define RHP_LOG_ID_XAUTH_AUTHENTICATOR_FAILED_TO_PROCESS_EAP_MESG	1444
#define RHP_LOG_ID_XAUTH_SERVER_AUTH_CONTINUE	1445
#define RHP_LOG_ID_XAUTH_SERVER_RX_PKT_VIA_UNCONFIGURED_IF	1446
#define RHP_LOG_ID_XAUTH_SERVER_AUTH_COMPLETED	1447
#define RHP_LOG_ID_XAUTH_SERVER_AUTH_ERROR	1448
#define RHP_LOG_ID_XAUTH_SERVER_AUTH_FAILED	1449
#define RHP_LOG_ID_RX_MODE_CFG_REQ_ATTR_PAYLOAD_ATTRS	1450
#define RHP_LOG_ID_RX_MODE_CFG_REQ_REJECT_NON_CLIENT	1451
#define RHP_LOG_ID_RX_MODE_CFG_REQ_CP_PAYLOAD_NOT_SUPPORTED_CFG_TYPE	1452
#define RHP_LOG_ID_RX_MODE_CFG_REQ_SUPPORTED_ATTRIBUTES	1453
#define RHP_LOG_ID_RX_MODE_CFG_REQ_OK	1454
#define RHP_LOG_ID_RX_MODE_CFG_REQ_TX_ERR_NOTIFY	1455
#define RHP_LOG_ID_RX_MODE_CFG_REQ_ERR	1456
#define RHP_LOG_ID_RX_MODE_CFG_CONFIG_SERVER_NOT_ENABLED	1457
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_RSASIG_PARSE_SIG_PAYLOAD_ERR	1458
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_HYBRID_AUTH_RSASIG_PARSE_HASH_PAYLOAD_ERR	1459
#define RHP_LOG_ID_CONNECT_I_IKEV1_NOT_ENABLED	1460
#define RHP_LOG_ID_CONNECT_I_IKEV1_MAIN_MODE_NOT_ENABLED	1461
#define RHP_LOG_ID_CONNECT_I_IKEV1_AGGRESSIVE_MODE_NOT_ENABLED	1462
#define RHP_LOG_ID_NHRP_CONNECT_SHORTCUT_PENDING	1463
#define RHP_LOG_ID_RX_IKEV1_DPD_R_U_THERE	1464
#define RHP_LOG_ID_RX_IKEV1_DPD_R_U_THERE_ERR	1465
#define RHP_LOG_ID_RX_IKEV1_DPD_R_U_THERE_ACK	1466
#define RHP_LOG_ID_RX_IKEV1_DPD_R_U_THERE_ACK_ERR	1467
#define RHP_LOG_ID_TX_IKEV1_DPD_R_U_THERE	1468
#define RHP_LOG_ID_TX_IKEV1_DPD_R_U_THERE_ERR	1469
#define RHP_LOG_ID_NHRP_TX_REGISTRATION_REQ_MESG_NOT_GRE_ENCAP	1470
#define RHP_LOG_ID_NHRP_TX_REGISTRATION_REQ_MESG_NO_HUB_OR_NHS_CONFIGURED	1471
#define RHP_LOG_ID_NHRP_RETRANSMIT_REGISTRATION_REQ_MESG_NOT_GRE_ENCAP	1472
#define RHP_LOG_ID_NHRP_RETRANSMIT_REGISTRATION_REQ_MESG_NO_HUB_OR_NHS_CONFIGURED	1473
#define RHP_LOG_ID_NHRP_RETRANSMIT_REGISTRATION_REQ_MESG	1474
#define RHP_LOG_ID_NHRP_RX_INVALID_AUTHENTICATION_EXT	1475
#define RHP_LOG_ID_NHRP_RX_MESG	1476
#define RHP_LOG_ID_NHRP_RX_INVALID_MESG	1477
#define RHP_LOG_ID_NHRP_RX_REGISTRATION_REQ	1478
#define RHP_LOG_ID_NHRP_RX_REGISTRATION_REQ_ERR	1479
#define RHP_LOG_ID_NHRP_RX_REGISTRATION_REP	1480
#define RHP_LOG_ID_NHRP_RX_REGISTRATION_REP_ERR	1481
#define RHP_LOG_ID_NHRP_TX_RESOLUTION_REP_RAW	1482
#define RHP_LOG_ID_NHRP_TX_RESOLUTION_REP_RAW_ERR	1483
#define RHP_LOG_ID_RX_IKEV1_MAIN_R_5_PARSE_CERT_REQ_PAYLOAD_ERR	1484

#endif // _RHP_LOG_H_
