#!/bin/sh

#
#  Copyright (C) 2009-2010 TETSUHARU HANADA <rhpenguine@gmail.com>
#  All rights reserved.
#  
#  You can redistribute and/or modify this software under the 
#  LESSER GPL version 2.1.
#  See also LICENSE.txt and LICENSE_LGPL2.1.txt.
#

if [ -e "/dev/rhp_file_trace" ]; then
  echo "$1" > "/dev/rhp_file_trace"      
fi

#logger "[ROCKHOPPER] $1"

#echo "[ROCKHOPPER] $1"

exit 0
